package dev.xdark.clientapi.block;

import dev.xdark.clientapi.*;
import dev.xdark.clientapi.util.*;

@SidedApi(Side.SERVER)
public final class Blocks
{
    public static final Block AIR;
    public static final Block STONE;
    public static final Block GRASS;
    public static final Block DIRT;
    public static final Block COBBLESTONE;
    public static final Block PLANKS;
    public static final Block SAPLING;
    public static final Block BEDROCK;
    public static final Block FLOWING_WATER;
    public static final Block WATER;
    public static final Block FLOWING_LAVA;
    public static final Block LAVA;
    public static final Block SAND;
    public static final Block GRAVEL;
    public static final Block GOLD_ORE;
    public static final Block IRON_ORE;
    public static final Block COAL_ORE;
    public static final Block LOG;
    public static final Block LOG2;
    public static final Block LEAVES;
    public static final Block LEAVES2;
    public static final Block SPONGE;
    public static final Block GLASS;
    public static final Block LAPIS_ORE;
    public static final Block LAPIS_BLOCK;
    public static final Block DISPENSER;
    public static final Block SANDSTONE;
    public static final Block NOTEBLOCK;
    public static final Block BED;
    public static final Block GOLDEN_RAIL;
    public static final Block DETECTOR_RAIL;
    public static final Block STICKY_PISTON;
    public static final Block WEB;
    public static final Block TALLGRASS;
    public static final Block DEADBUSH;
    public static final Block PISTON;
    public static final Block PISTON_HEAD;
    public static final Block WOOL;
    public static final Block PISTON_EXTENSION;
    public static final Block YELLOW_FLOWER;
    public static final Block RED_FLOWER;
    public static final Block BROWN_MUSHROOM;
    public static final Block RED_MUSHROOM;
    public static final Block GOLD_BLOCK;
    public static final Block IRON_BLOCK;
    public static final Block DOUBLE_STONE_SLAB;
    public static final Block STONE_SLAB;
    public static final Block BRICK_BLOCK;
    public static final Block TNT;
    public static final Block BOOKSHELF;
    public static final Block MOSSY_COBBLESTONE;
    public static final Block OBSIDIAN;
    public static final Block TORCH;
    public static final Block FIRE;
    public static final Block MOB_SPAWNER;
    public static final Block OAK_STAIRS;
    public static final Block CHEST;
    public static final Block REDSTONE_WIRE;
    public static final Block DIAMOND_ORE;
    public static final Block DIAMOND_BLOCK;
    public static final Block CRAFTING_TABLE;
    public static final Block WHEAT;
    public static final Block FARMLAND;
    public static final Block FURNACE;
    public static final Block LIT_FURNACE;
    public static final Block STANDING_SIGN;
    public static final Block OAK_DOOR;
    public static final Block SPRUCE_DOOR;
    public static final Block BIRCH_DOOR;
    public static final Block JUNGLE_DOOR;
    public static final Block ACACIA_DOOR;
    public static final Block DARK_OAK_DOOR;
    public static final Block LADDER;
    public static final Block RAIL;
    public static final Block STONE_STAIRS;
    public static final Block WALL_SIGN;
    public static final Block LEVER;
    public static final Block STONE_PRESSURE_PLATE;
    public static final Block IRON_DOOR;
    public static final Block WOODEN_PRESSURE_PLATE;
    public static final Block REDSTONE_ORE;
    public static final Block LIT_REDSTONE_ORE;
    public static final Block UNLIT_REDSTONE_TORCH;
    public static final Block REDSTONE_TORCH;
    public static final Block STONE_BUTTON;
    public static final Block SNOW_LAYER;
    public static final Block ICE;
    public static final Block SNOW;
    public static final Block CACTUS;
    public static final Block CLAY;
    public static final Block REEDS;
    public static final Block JUKEBOX;
    public static final Block OAK_FENCE;
    public static final Block SPRUCE_FENCE;
    public static final Block BIRCH_FENCE;
    public static final Block JUNGLE_FENCE;
    public static final Block DARK_OAK_FENCE;
    public static final Block ACACIA_FENCE;
    public static final Block PUMPKIN;
    public static final Block NETHERRACK;
    public static final Block SOUL_SAND;
    public static final Block GLOWSTONE;
    public static final Block PORTAL;
    public static final Block LIT_PUMPKIN;
    public static final Block CAKE;
    public static final Block UNPOWERED_REPEATER;
    public static final Block POWERED_REPEATER;
    public static final Block TRAPDOOR;
    public static final Block MONSTER_EGG;
    public static final Block STONEBRICK;
    public static final Block BROWN_MUSHROOM_BLOCK;
    public static final Block RED_MUSHROOM_BLOCK;
    public static final Block IRON_BARS;
    public static final Block GLASS_PANE;
    public static final Block MELON_BLOCK;
    public static final Block PUMPKIN_STEM;
    public static final Block MELON_STEM;
    public static final Block VINE;
    public static final Block OAK_FENCE_GATE;
    public static final Block SPRUCE_FENCE_GATE;
    public static final Block BIRCH_FENCE_GATE;
    public static final Block JUNGLE_FENCE_GATE;
    public static final Block DARK_OAK_FENCE_GATE;
    public static final Block ACACIA_FENCE_GATE;
    public static final Block BRICK_STAIRS;
    public static final Block STONE_BRICK_STAIRS;
    public static final Block MYCELIUM;
    public static final Block WATERLILY;
    public static final Block NETHER_BRICK;
    public static final Block NETHER_BRICK_FENCE;
    public static final Block NETHER_BRICK_STAIRS;
    public static final Block NETHER_WART;
    public static final Block ENCHANTING_TABLE;
    public static final Block BREWING_STAND;
    public static final Block CAULDRON;
    public static final Block END_PORTAL;
    public static final Block END_PORTAL_FRAME;
    public static final Block END_STONE;
    public static final Block DRAGON_EGG;
    public static final Block REDSTONE_LAMP;
    public static final Block LIT_REDSTONE_LAMP;
    public static final Block DOUBLE_WOODEN_SLAB;
    public static final Block WOODEN_SLAB;
    public static final Block COCOA;
    public static final Block SANDSTONE_STAIRS;
    public static final Block EMERALD_ORE;
    public static final Block ENDER_CHEST;
    public static final Block TRIPWIRE_HOOK;
    public static final Block TRIPWIRE;
    public static final Block EMERALD_BLOCK;
    public static final Block SPRUCE_STAIRS;
    public static final Block BIRCH_STAIRS;
    public static final Block JUNGLE_STAIRS;
    public static final Block COMMAND_BLOCK;
    public static final Block BEACON;
    public static final Block COBBLESTONE_WALL;
    public static final Block FLOWER_POT;
    public static final Block CARROTS;
    public static final Block POTATOES;
    public static final Block WOODEN_BUTTON;
    public static final Block SKULL;
    public static final Block ANVIL;
    public static final Block TRAPPED_CHEST;
    public static final Block LIGHT_WEIGHTED_PRESSURE_PLATE;
    public static final Block HEAVY_WEIGHTED_PRESSURE_PLATE;
    public static final Block UNPOWERED_COMPARATOR;
    public static final Block POWERED_COMPARATOR;
    public static final Block DAYLIGHT_DETECTOR;
    public static final Block DAYLIGHT_DETECTOR_INVERTED;
    public static final Block REDSTONE_BLOCK;
    public static final Block QUARTZ_ORE;
    public static final Block HOPPER;
    public static final Block QUARTZ_BLOCK;
    public static final Block QUARTZ_STAIRS;
    public static final Block ACTIVATOR_RAIL;
    public static final Block DROPPER;
    public static final Block STAINED_HARDENED_CLAY;
    public static final Block BARRIER;
    public static final Block IRON_TRAPDOOR;
    public static final Block HAY_BLOCK;
    public static final Block CARPET;
    public static final Block HARDENED_CLAY;
    public static final Block COAL_BLOCK;
    public static final Block PACKED_ICE;
    public static final Block ACACIA_STAIRS;
    public static final Block DARK_OAK_STAIRS;
    public static final Block SLIME_BLOCK;
    public static final Block DOUBLE_PLANT;
    public static final Block STAINED_GLASS;
    public static final Block STAINED_GLASS_PANE;
    public static final Block PRISMARINE;
    public static final Block SEA_LANTERN;
    public static final Block STANDING_BANNER;
    public static final Block WALL_BANNER;
    public static final Block RED_SANDSTONE;
    public static final Block RED_SANDSTONE_STAIRS;
    public static final Block DOUBLE_STONE_SLAB2;
    public static final Block STONE_SLAB2;
    public static final Block END_ROD;
    public static final Block CHORUS_PLANT;
    public static final Block CHORUS_FLOWER;
    public static final Block PURPUR_BLOCK;
    public static final Block PURPUR_PILLAR;
    public static final Block PURPUR_STAIRS;
    public static final Block PURPUR_DOUBLE_SLAB;
    public static final Block PURPUR_SLAB;
    public static final Block END_BRICKS;
    public static final Block BEETROOTS;
    public static final Block GRASS_PATH;
    public static final Block END_GATEWAY;
    public static final Block REPEATING_COMMAND_BLOCK;
    public static final Block CHAIN_COMMAND_BLOCK;
    public static final Block FROSTED_ICE;
    public static final Block MAGMA;
    public static final Block NETHER_WART_BLOCK;
    public static final Block RED_NETHER_BRICK;
    public static final Block BONE_BLOCK;
    public static final Block STRUCTURE_VOID;
    public static final Block OBSERVER;
    public static final Block WHITE_SHULKER_BOX;
    public static final Block ORANGE_SHULKER_BOX;
    public static final Block MAGENTA_SHULKER_BOX;
    public static final Block LIGHT_BLUE_SHULKER_BOX;
    public static final Block YELLOW_SHULKER_BOX;
    public static final Block LIME_SHULKER_BOX;
    public static final Block PINK_SHULKER_BOX;
    public static final Block GRAY_SHULKER_BOX;
    public static final Block SILVER_SHULKER_BOX;
    public static final Block CYAN_SHULKER_BOX;
    public static final Block PURPLE_SHULKER_BOX;
    public static final Block BLUE_SHULKER_BOX;
    public static final Block BROWN_SHULKER_BOX;
    public static final Block GREEN_SHULKER_BOX;
    public static final Block RED_SHULKER_BOX;
    public static final Block BLACK_SHULKER_BOX;
    public static final Block WHITE_GLAZED_TERRACOTTA;
    public static final Block ORANGE_GLAZED_TERRACOTTA;
    public static final Block MAGENTA_GLAZED_TERRACOTTA;
    public static final Block LIGHT_BLUE_GLAZED_TERRACOTTA;
    public static final Block YELLOW_GLAZED_TERRACOTTA;
    public static final Block LIME_GLAZED_TERRACOTTA;
    public static final Block PINK_GLAZED_TERRACOTTA;
    public static final Block GRAY_GLAZED_TERRACOTTA;
    public static final Block SILVER_GLAZED_TERRACOTTA;
    public static final Block CYAN_GLAZED_TERRACOTTA;
    public static final Block PURPLE_GLAZED_TERRACOTTA;
    public static final Block BLUE_GLAZED_TERRACOTTA;
    public static final Block BROWN_GLAZED_TERRACOTTA;
    public static final Block GREEN_GLAZED_TERRACOTTA;
    public static final Block RED_GLAZED_TERRACOTTA;
    public static final Block BLACK_GLAZED_TERRACOTTA;
    public static final Block CONCRETE;
    public static final Block CONCRETE_POWDER;
    public static final Block STRUCTURE_BLOCK;
    public static final Block BLUE_ICE;
    public static final Block DEAD_TUBE_CORAL;
    public static final Block DEAD_BRAIN_CORAL;
    public static final Block DEAD_BUBBLE_CORAL;
    public static final Block DEAD_FIRE_CORAL;
    public static final Block DEAD_HORN_CORAL;
    public static final Block TUBE_CORAL;
    public static final Block BRAIN_CORAL;
    public static final Block BUBBLE_CORAL;
    public static final Block FIRE_CORAL;
    public static final Block HORN_CORAL;
    public static final Block NETHERITE;
    public static final Block CRYING_OBSIDIAN;
    public static final Block CRIMSON_NYLIUM;
    public static final Block WARPED_NYLIUM;
    public static final Block TARGET;
    public static final Block LODESTONE;
    public static final Block HONEY;
    public static final Block SHROOMLIGHT;
    
    private Blocks() {
    }
    
    static {
        AIR = SideEffects.objectValue();
        STONE = SideEffects.objectValue();
        GRASS = SideEffects.objectValue();
        DIRT = SideEffects.objectValue();
        COBBLESTONE = SideEffects.objectValue();
        PLANKS = SideEffects.objectValue();
        SAPLING = SideEffects.objectValue();
        BEDROCK = SideEffects.objectValue();
        FLOWING_WATER = SideEffects.objectValue();
        WATER = SideEffects.objectValue();
        FLOWING_LAVA = SideEffects.objectValue();
        LAVA = SideEffects.objectValue();
        SAND = SideEffects.objectValue();
        GRAVEL = SideEffects.objectValue();
        GOLD_ORE = SideEffects.objectValue();
        IRON_ORE = SideEffects.objectValue();
        COAL_ORE = SideEffects.objectValue();
        LOG = SideEffects.objectValue();
        LOG2 = SideEffects.objectValue();
        LEAVES = SideEffects.objectValue();
        LEAVES2 = SideEffects.objectValue();
        SPONGE = SideEffects.objectValue();
        GLASS = SideEffects.objectValue();
        LAPIS_ORE = SideEffects.objectValue();
        LAPIS_BLOCK = SideEffects.objectValue();
        DISPENSER = SideEffects.objectValue();
        SANDSTONE = SideEffects.objectValue();
        NOTEBLOCK = SideEffects.objectValue();
        BED = SideEffects.objectValue();
        GOLDEN_RAIL = SideEffects.objectValue();
        DETECTOR_RAIL = SideEffects.objectValue();
        STICKY_PISTON = SideEffects.objectValue();
        WEB = SideEffects.objectValue();
        TALLGRASS = SideEffects.objectValue();
        DEADBUSH = SideEffects.objectValue();
        PISTON = SideEffects.objectValue();
        PISTON_HEAD = SideEffects.objectValue();
        WOOL = SideEffects.objectValue();
        PISTON_EXTENSION = SideEffects.objectValue();
        YELLOW_FLOWER = SideEffects.objectValue();
        RED_FLOWER = SideEffects.objectValue();
        BROWN_MUSHROOM = SideEffects.objectValue();
        RED_MUSHROOM = SideEffects.objectValue();
        GOLD_BLOCK = SideEffects.objectValue();
        IRON_BLOCK = SideEffects.objectValue();
        DOUBLE_STONE_SLAB = SideEffects.objectValue();
        STONE_SLAB = SideEffects.objectValue();
        BRICK_BLOCK = SideEffects.objectValue();
        TNT = SideEffects.objectValue();
        BOOKSHELF = SideEffects.objectValue();
        MOSSY_COBBLESTONE = SideEffects.objectValue();
        OBSIDIAN = SideEffects.objectValue();
        TORCH = SideEffects.objectValue();
        FIRE = SideEffects.objectValue();
        MOB_SPAWNER = SideEffects.objectValue();
        OAK_STAIRS = SideEffects.objectValue();
        CHEST = SideEffects.objectValue();
        REDSTONE_WIRE = SideEffects.objectValue();
        DIAMOND_ORE = SideEffects.objectValue();
        DIAMOND_BLOCK = SideEffects.objectValue();
        CRAFTING_TABLE = SideEffects.objectValue();
        WHEAT = SideEffects.objectValue();
        FARMLAND = SideEffects.objectValue();
        FURNACE = SideEffects.objectValue();
        LIT_FURNACE = SideEffects.objectValue();
        STANDING_SIGN = SideEffects.objectValue();
        OAK_DOOR = SideEffects.objectValue();
        SPRUCE_DOOR = SideEffects.objectValue();
        BIRCH_DOOR = SideEffects.objectValue();
        JUNGLE_DOOR = SideEffects.objectValue();
        ACACIA_DOOR = SideEffects.objectValue();
        DARK_OAK_DOOR = SideEffects.objectValue();
        LADDER = SideEffects.objectValue();
        RAIL = SideEffects.objectValue();
        STONE_STAIRS = SideEffects.objectValue();
        WALL_SIGN = SideEffects.objectValue();
        LEVER = SideEffects.objectValue();
        STONE_PRESSURE_PLATE = SideEffects.objectValue();
        IRON_DOOR = SideEffects.objectValue();
        WOODEN_PRESSURE_PLATE = SideEffects.objectValue();
        REDSTONE_ORE = SideEffects.objectValue();
        LIT_REDSTONE_ORE = SideEffects.objectValue();
        UNLIT_REDSTONE_TORCH = SideEffects.objectValue();
        REDSTONE_TORCH = SideEffects.objectValue();
        STONE_BUTTON = SideEffects.objectValue();
        SNOW_LAYER = SideEffects.objectValue();
        ICE = SideEffects.objectValue();
        SNOW = SideEffects.objectValue();
        CACTUS = SideEffects.objectValue();
        CLAY = SideEffects.objectValue();
        REEDS = SideEffects.objectValue();
        JUKEBOX = SideEffects.objectValue();
        OAK_FENCE = SideEffects.objectValue();
        SPRUCE_FENCE = SideEffects.objectValue();
        BIRCH_FENCE = SideEffects.objectValue();
        JUNGLE_FENCE = SideEffects.objectValue();
        DARK_OAK_FENCE = SideEffects.objectValue();
        ACACIA_FENCE = SideEffects.objectValue();
        PUMPKIN = SideEffects.objectValue();
        NETHERRACK = SideEffects.objectValue();
        SOUL_SAND = SideEffects.objectValue();
        GLOWSTONE = SideEffects.objectValue();
        PORTAL = SideEffects.objectValue();
        LIT_PUMPKIN = SideEffects.objectValue();
        CAKE = SideEffects.objectValue();
        UNPOWERED_REPEATER = SideEffects.objectValue();
        POWERED_REPEATER = SideEffects.objectValue();
        TRAPDOOR = SideEffects.objectValue();
        MONSTER_EGG = SideEffects.objectValue();
        STONEBRICK = SideEffects.objectValue();
        BROWN_MUSHROOM_BLOCK = SideEffects.objectValue();
        RED_MUSHROOM_BLOCK = SideEffects.objectValue();
        IRON_BARS = SideEffects.objectValue();
        GLASS_PANE = SideEffects.objectValue();
        MELON_BLOCK = SideEffects.objectValue();
        PUMPKIN_STEM = SideEffects.objectValue();
        MELON_STEM = SideEffects.objectValue();
        VINE = SideEffects.objectValue();
        OAK_FENCE_GATE = SideEffects.objectValue();
        SPRUCE_FENCE_GATE = SideEffects.objectValue();
        BIRCH_FENCE_GATE = SideEffects.objectValue();
        JUNGLE_FENCE_GATE = SideEffects.objectValue();
        DARK_OAK_FENCE_GATE = SideEffects.objectValue();
        ACACIA_FENCE_GATE = SideEffects.objectValue();
        BRICK_STAIRS = SideEffects.objectValue();
        STONE_BRICK_STAIRS = SideEffects.objectValue();
        MYCELIUM = SideEffects.objectValue();
        WATERLILY = SideEffects.objectValue();
        NETHER_BRICK = SideEffects.objectValue();
        NETHER_BRICK_FENCE = SideEffects.objectValue();
        NETHER_BRICK_STAIRS = SideEffects.objectValue();
        NETHER_WART = SideEffects.objectValue();
        ENCHANTING_TABLE = SideEffects.objectValue();
        BREWING_STAND = SideEffects.objectValue();
        CAULDRON = SideEffects.objectValue();
        END_PORTAL = SideEffects.objectValue();
        END_PORTAL_FRAME = SideEffects.objectValue();
        END_STONE = SideEffects.objectValue();
        DRAGON_EGG = SideEffects.objectValue();
        REDSTONE_LAMP = SideEffects.objectValue();
        LIT_REDSTONE_LAMP = SideEffects.objectValue();
        DOUBLE_WOODEN_SLAB = SideEffects.objectValue();
        WOODEN_SLAB = SideEffects.objectValue();
        COCOA = SideEffects.objectValue();
        SANDSTONE_STAIRS = SideEffects.objectValue();
        EMERALD_ORE = SideEffects.objectValue();
        ENDER_CHEST = SideEffects.objectValue();
        TRIPWIRE_HOOK = SideEffects.objectValue();
        TRIPWIRE = SideEffects.objectValue();
        EMERALD_BLOCK = SideEffects.objectValue();
        SPRUCE_STAIRS = SideEffects.objectValue();
        BIRCH_STAIRS = SideEffects.objectValue();
        JUNGLE_STAIRS = SideEffects.objectValue();
        COMMAND_BLOCK = SideEffects.objectValue();
        BEACON = SideEffects.objectValue();
        COBBLESTONE_WALL = SideEffects.objectValue();
        FLOWER_POT = SideEffects.objectValue();
        CARROTS = SideEffects.objectValue();
        POTATOES = SideEffects.objectValue();
        WOODEN_BUTTON = SideEffects.objectValue();
        SKULL = SideEffects.objectValue();
        ANVIL = SideEffects.objectValue();
        TRAPPED_CHEST = SideEffects.objectValue();
        LIGHT_WEIGHTED_PRESSURE_PLATE = SideEffects.objectValue();
        HEAVY_WEIGHTED_PRESSURE_PLATE = SideEffects.objectValue();
        UNPOWERED_COMPARATOR = SideEffects.objectValue();
        POWERED_COMPARATOR = SideEffects.objectValue();
        DAYLIGHT_DETECTOR = SideEffects.objectValue();
        DAYLIGHT_DETECTOR_INVERTED = SideEffects.objectValue();
        REDSTONE_BLOCK = SideEffects.objectValue();
        QUARTZ_ORE = SideEffects.objectValue();
        HOPPER = SideEffects.objectValue();
        QUARTZ_BLOCK = SideEffects.objectValue();
        QUARTZ_STAIRS = SideEffects.objectValue();
        ACTIVATOR_RAIL = SideEffects.objectValue();
        DROPPER = SideEffects.objectValue();
        STAINED_HARDENED_CLAY = SideEffects.objectValue();
        BARRIER = SideEffects.objectValue();
        IRON_TRAPDOOR = SideEffects.objectValue();
        HAY_BLOCK = SideEffects.objectValue();
        CARPET = SideEffects.objectValue();
        HARDENED_CLAY = SideEffects.objectValue();
        COAL_BLOCK = SideEffects.objectValue();
        PACKED_ICE = SideEffects.objectValue();
        ACACIA_STAIRS = SideEffects.objectValue();
        DARK_OAK_STAIRS = SideEffects.objectValue();
        SLIME_BLOCK = SideEffects.objectValue();
        DOUBLE_PLANT = SideEffects.objectValue();
        STAINED_GLASS = SideEffects.objectValue();
        STAINED_GLASS_PANE = SideEffects.objectValue();
        PRISMARINE = SideEffects.objectValue();
        SEA_LANTERN = SideEffects.objectValue();
        STANDING_BANNER = SideEffects.objectValue();
        WALL_BANNER = SideEffects.objectValue();
        RED_SANDSTONE = SideEffects.objectValue();
        RED_SANDSTONE_STAIRS = SideEffects.objectValue();
        DOUBLE_STONE_SLAB2 = SideEffects.objectValue();
        STONE_SLAB2 = SideEffects.objectValue();
        END_ROD = SideEffects.objectValue();
        CHORUS_PLANT = SideEffects.objectValue();
        CHORUS_FLOWER = SideEffects.objectValue();
        PURPUR_BLOCK = SideEffects.objectValue();
        PURPUR_PILLAR = SideEffects.objectValue();
        PURPUR_STAIRS = SideEffects.objectValue();
        PURPUR_DOUBLE_SLAB = SideEffects.objectValue();
        PURPUR_SLAB = SideEffects.objectValue();
        END_BRICKS = SideEffects.objectValue();
        BEETROOTS = SideEffects.objectValue();
        GRASS_PATH = SideEffects.objectValue();
        END_GATEWAY = SideEffects.objectValue();
        REPEATING_COMMAND_BLOCK = SideEffects.objectValue();
        CHAIN_COMMAND_BLOCK = SideEffects.objectValue();
        FROSTED_ICE = SideEffects.objectValue();
        MAGMA = SideEffects.objectValue();
        NETHER_WART_BLOCK = SideEffects.objectValue();
        RED_NETHER_BRICK = SideEffects.objectValue();
        BONE_BLOCK = SideEffects.objectValue();
        STRUCTURE_VOID = SideEffects.objectValue();
        OBSERVER = SideEffects.objectValue();
        WHITE_SHULKER_BOX = SideEffects.objectValue();
        ORANGE_SHULKER_BOX = SideEffects.objectValue();
        MAGENTA_SHULKER_BOX = SideEffects.objectValue();
        LIGHT_BLUE_SHULKER_BOX = SideEffects.objectValue();
        YELLOW_SHULKER_BOX = SideEffects.objectValue();
        LIME_SHULKER_BOX = SideEffects.objectValue();
        PINK_SHULKER_BOX = SideEffects.objectValue();
        GRAY_SHULKER_BOX = SideEffects.objectValue();
        SILVER_SHULKER_BOX = SideEffects.objectValue();
        CYAN_SHULKER_BOX = SideEffects.objectValue();
        PURPLE_SHULKER_BOX = SideEffects.objectValue();
        BLUE_SHULKER_BOX = SideEffects.objectValue();
        BROWN_SHULKER_BOX = SideEffects.objectValue();
        GREEN_SHULKER_BOX = SideEffects.objectValue();
        RED_SHULKER_BOX = SideEffects.objectValue();
        BLACK_SHULKER_BOX = SideEffects.objectValue();
        WHITE_GLAZED_TERRACOTTA = SideEffects.objectValue();
        ORANGE_GLAZED_TERRACOTTA = SideEffects.objectValue();
        MAGENTA_GLAZED_TERRACOTTA = SideEffects.objectValue();
        LIGHT_BLUE_GLAZED_TERRACOTTA = SideEffects.objectValue();
        YELLOW_GLAZED_TERRACOTTA = SideEffects.objectValue();
        LIME_GLAZED_TERRACOTTA = SideEffects.objectValue();
        PINK_GLAZED_TERRACOTTA = SideEffects.objectValue();
        GRAY_GLAZED_TERRACOTTA = SideEffects.objectValue();
        SILVER_GLAZED_TERRACOTTA = SideEffects.objectValue();
        CYAN_GLAZED_TERRACOTTA = SideEffects.objectValue();
        PURPLE_GLAZED_TERRACOTTA = SideEffects.objectValue();
        BLUE_GLAZED_TERRACOTTA = SideEffects.objectValue();
        BROWN_GLAZED_TERRACOTTA = SideEffects.objectValue();
        GREEN_GLAZED_TERRACOTTA = SideEffects.objectValue();
        RED_GLAZED_TERRACOTTA = SideEffects.objectValue();
        BLACK_GLAZED_TERRACOTTA = SideEffects.objectValue();
        CONCRETE = SideEffects.objectValue();
        CONCRETE_POWDER = SideEffects.objectValue();
        STRUCTURE_BLOCK = SideEffects.objectValue();
        BLUE_ICE = SideEffects.objectValue();
        DEAD_TUBE_CORAL = SideEffects.objectValue();
        DEAD_BRAIN_CORAL = SideEffects.objectValue();
        DEAD_BUBBLE_CORAL = SideEffects.objectValue();
        DEAD_FIRE_CORAL = SideEffects.objectValue();
        DEAD_HORN_CORAL = SideEffects.objectValue();
        TUBE_CORAL = SideEffects.objectValue();
        BRAIN_CORAL = SideEffects.objectValue();
        BUBBLE_CORAL = SideEffects.objectValue();
        FIRE_CORAL = SideEffects.objectValue();
        HORN_CORAL = SideEffects.objectValue();
        NETHERITE = SideEffects.objectValue();
        CRYING_OBSIDIAN = SideEffects.objectValue();
        CRIMSON_NYLIUM = SideEffects.objectValue();
        WARPED_NYLIUM = SideEffects.objectValue();
        TARGET = SideEffects.objectValue();
        LODESTONE = SideEffects.objectValue();
        HONEY = SideEffects.objectValue();
        SHROOMLIGHT = SideEffects.objectValue();
    }
}
