package dev.xdark.clientapi.sound;

import dev.xdark.clientapi.*;
import dev.xdark.clientapi.util.*;

@SidedApi(Side.SERVER)
public final class SoundEvents
{
    public static final SoundEvent AMBIENT_CAVE;
    public static final SoundEvent BLOCK_ANVIL_BREAK;
    public static final SoundEvent BLOCK_ANVIL_DESTROY;
    public static final SoundEvent BLOCK_ANVIL_FALL;
    public static final SoundEvent BLOCK_ANVIL_HIT;
    public static final SoundEvent BLOCK_ANVIL_LAND;
    public static final SoundEvent BLOCK_ANVIL_PLACE;
    public static final SoundEvent BLOCK_ANVIL_STEP;
    public static final SoundEvent BLOCK_ANVIL_USE;
    public static final SoundEvent ENTITY_ARMORSTAND_BREAK;
    public static final SoundEvent ENTITY_ARMORSTAND_FALL;
    public static final SoundEvent ENTITY_ARMORSTAND_HIT;
    public static final SoundEvent ENTITY_ARMORSTAND_PLACE;
    public static final SoundEvent ITEM_ARMOR_EQUIP_CHAIN;
    public static final SoundEvent ITEM_ARMOR_EQUIP_DIAMOND;
    public static final SoundEvent ITEM_ARMOR_EQIIP_ELYTRA;
    public static final SoundEvent ITEM_ARMOR_EQUIP_GENERIC;
    public static final SoundEvent ITEM_ARMOR_EQUIP_GOLD;
    public static final SoundEvent ITEM_ARMOR_EQUIP_IRON;
    public static final SoundEvent ITEM_ARMOR_EQUIP_LEATHER;
    public static final SoundEvent ENTITY_ARROW_HIT;
    public static final SoundEvent ENTITY_ARROW_HIT_PLAYER;
    public static final SoundEvent ENTITY_ARROW_SHOOT;
    public static final SoundEvent ENTITY_BAT_AMBIENT;
    public static final SoundEvent ENTITY_BAT_DEATH;
    public static final SoundEvent ENTITY_BAT_HURT;
    public static final SoundEvent ENTITY_BAT_LOOP;
    public static final SoundEvent ENTITY_BAT_TAKEOFF;
    public static final SoundEvent ENTITY_BLAZE_AMBIENT;
    public static final SoundEvent ENTITY_BLAZE_BURN;
    public static final SoundEvent ENTITY_BLAZE_DEATH;
    public static final SoundEvent ENTITY_BLAZE_HURT;
    public static final SoundEvent ENTITY_BLAZE_SHOOT;
    public static final SoundEvent ENTITY_BOAT_PADDLE_LAND;
    public static final SoundEvent ENTITY_BOAT_PADDLE_WATER;
    public static final SoundEvent ENTITY_BOBBER_RETRIEVE;
    public static final SoundEvent ENTITY_BOBBER_SPLASH;
    public static final SoundEvent ENTITY_BOBBER_THROW;
    public static final SoundEvent ITEM_BOTTLE_EMPTY;
    public static final SoundEvent ITEM_BOTTLE_FILL;
    public static final SoundEvent ITEM_BOTTLE_FILL_DRAGONBREATH;
    public static final SoundEvent BLOCK_BREWING_STAND_BREW;
    public static final SoundEvent ITEM_BUCKET_EMPTY;
    public static final SoundEvent ITEM_BUCKET_EMPTY_LAVA;
    public static final SoundEvent ITEM_BUCKET_FILL;
    public static final SoundEvent ITEM_BUCKET_FILL_LAVA;
    public static final SoundEvent ENTITY_CAT_AMBIENT;
    public static final SoundEvent ENTITY_CAT_DEATH;
    public static final SoundEvent ENTITY_CAT_HISS;
    public static final SoundEvent ENTITY_CAT_HURT;
    public static final SoundEvent ENTITY_CAT_PURR;
    public static final SoundEvent ENTITY_CAT_PURREOW;
    public static final SoundEvent BLOCK_CHEST_CLOSE;
    public static final SoundEvent BLOCK_CHEST_LOCKED;
    public static final SoundEvent BLOCK_CHEST_OPEN;
    public static final SoundEvent ENTITY_CHICKEN_AMBIENT;
    public static final SoundEvent ENTITY_CHICKEN_DEATH;
    public static final SoundEvent ENTITY_CHICKEN_EGG;
    public static final SoundEvent ENTITY_CHICKEN_HURT;
    public static final SoundEvent ENTITY_CHICKEN_STEP;
    public static final SoundEvent BLOCK_CHORUS_FLOWER_DEATH;
    public static final SoundEvent BLOCK_CHORUS_FLOWER_GROW;
    public static final SoundEvent ITEM_CHORUS_FRUIT_TELEPORT;
    public static final SoundEvent BLOCK_CLOTH_BREAK;
    public static final SoundEvent BLOCK_CLOTH_FALL;
    public static final SoundEvent BLOCK_CLOTH_HIT;
    public static final SoundEvent BLOCK_CLOTH_PLACE;
    public static final SoundEvent BLOCK_CLOTH_STEP;
    public static final SoundEvent BLOCK_COMPARATOR_CLICK;
    public static final SoundEvent ENTITY_COW_AMBIENT;
    public static final SoundEvent ENTITY_COW_DEATH;
    public static final SoundEvent ENTITY_COW_HURT;
    public static final SoundEvent ENTITY_COW_MILK;
    public static final SoundEvent ENTITY_COW_STEP;
    public static final SoundEvent ENTITY_CREEPER_DEATH;
    public static final SoundEvent ENTITY_CREEPER_HURT;
    public static final SoundEvent ENTITY_CREEPER_PRIMED;
    public static final SoundEvent BLOCK_DISPENSER_DISPENSE;
    public static final SoundEvent BLOCK_DISPENSER_FAIL;
    public static final SoundEvent BLOCK_DISPENSER_LAUNCH;
    public static final SoundEvent ENTITY_DONKEY_AMBIENT;
    public static final SoundEvent ENTITY_DONKEY_ANGRY;
    public static final SoundEvent ENTITY_DONKEY_CHEST;
    public static final SoundEvent ENTITY_DONKEY_DEATH;
    public static final SoundEvent ENTITY_DONKEY_HURT;
    public static final SoundEvent ENTITY_EGG_THROW;
    public static final SoundEvent ENTITY_ELDER_GUARDIAN_AMBIENT;
    public static final SoundEvent ENTITY_ELDERGUARDIAN_AMBIENTLAND;
    public static final SoundEvent ENTITY_ELDER_GUARDIAN_CURSE;
    public static final SoundEvent ENTITY_ELDER_GUARDIAN_DEATH;
    public static final SoundEvent ENTITY_ELDER_GUARDIAN_DEATH_LAND;
    public static final SoundEvent ENTITY_ELDER_GUARDIAN_FLOP;
    public static final SoundEvent ENTITY_ELDER_GUARDIAN_HURT;
    public static final SoundEvent ENTITY_ELDER_GUARDIAN_HURT_LAND;
    public static final SoundEvent ITEM_ELYTRA_FLYING;
    public static final SoundEvent BLOCK_ENCHANTMENT_TABLE_USE;
    public static final SoundEvent BLOCK_ENDERCHEST_CLOSE;
    public static final SoundEvent BLOCK_ENDERCHEST_OPEN;
    public static final SoundEvent ENTITY_ENDERDRAGON_AMBIENT;
    public static final SoundEvent ENTITY_ENDERDRAGON_DEATH;
    public static final SoundEvent ENTITY_ENDERDRAGON_FIREBALL_EPLD;
    public static final SoundEvent ENTITY_ENDERDRAGON_FLAP;
    public static final SoundEvent ENTITY_ENDERDRAGON_GROWL;
    public static final SoundEvent ENTITY_ENDERDRAGON_HURT;
    public static final SoundEvent ENTITY_ENDERDRAGON_SHOOT;
    public static final SoundEvent ENTITY_ENDEREYE_DEATH;
    public static final SoundEvent ENTITY_ENDEREYE_LAUNCH;
    public static final SoundEvent ENTITY_ENDERMEN_AMBIENT;
    public static final SoundEvent ENTITY_ENDERMEN_DEATH;
    public static final SoundEvent ENTITY_ENDERMEN_HURT;
    public static final SoundEvent ENTITY_ENDERMEN_SCREAM;
    public static final SoundEvent ENTITY_ENDERMEN_STARE;
    public static final SoundEvent ENTITY_ENDERMEN_TELEPORT;
    public static final SoundEvent ENTITY_ENDERMITE_AMBIENT;
    public static final SoundEvent ENTITY_ENDERMITE_DEATH;
    public static final SoundEvent ENTITY_ENDERMITE_HURT;
    public static final SoundEvent ENTITY_ENDERMITE_STEP;
    public static final SoundEvent ENTITY_ENDERPEARL_THROW;
    public static final SoundEvent BLOCK_END_GATEWAY_SPAWN;
    public static final SoundEvent BLOCK_END_PORTAL_FRAME_FILL;
    public static final SoundEvent BLOCK_END_PORTAL_SPAWN;
    public static final SoundEvent EVOCATION_FANGS_ATTACK;
    public static final SoundEvent ENTITY_EVOCATION_ILLAGER_AMBIENT;
    public static final SoundEvent EVOCATION_ILLAGER_CAST_SPELL;
    public static final SoundEvent EVOCATION_ILLAGER_DEATH;
    public static final SoundEvent ENTITY_EVOCATION_ILLAGER_HURT;
    public static final SoundEvent EVOCATION_ILLAGER_PREPARE_ATTACK;
    public static final SoundEvent EVOCATION_ILLAGER_PREPARE_SUMMON;
    public static final SoundEvent EVOCATION_ILLAGER_PREPARE_WOLOLO;
    public static final SoundEvent ENTITY_EXPERIENCE_BOTTLE_THROW;
    public static final SoundEvent ENTITY_EXPERIENCE_ORB_PICKUP;
    public static final SoundEvent BLOCK_FENCE_GATE_CLOSE;
    public static final SoundEvent BLOCK_FENCE_GATE_OPEN;
    public static final SoundEvent ITEM_FIRECHARGE_USE;
    public static final SoundEvent ENTITY_FIREWORK_BLAST;
    public static final SoundEvent ENTITY_FIREWORK_BLAST_FAR;
    public static final SoundEvent ENTITY_FIREWORK_LARGE_BLAST;
    public static final SoundEvent ENTITY_FIREWORK_LARGE_BLAST_FAR;
    public static final SoundEvent ENTITY_FIREWORK_LAUNCH;
    public static final SoundEvent ENTITY_FIREWORK_SHOOT;
    public static final SoundEvent ENTITY_FIREWORK_TWINKLE;
    public static final SoundEvent ENTITY_FIREWORK_TWINKLE_FAR;
    public static final SoundEvent BLOCK_FIRE_AMBIENT;
    public static final SoundEvent BLOCK_FIRE_EXTINGUISH;
    public static final SoundEvent ITEM_FLINTANDSTEEL_USE;
    public static final SoundEvent BLOCK_FURNACE_FIRE_CRACKLE;
    public static final SoundEvent ENTITY_GENERIC_BIG_FALL;
    public static final SoundEvent ENTITY_GENERIC_BURN;
    public static final SoundEvent ENTITY_GENERIC_DEATH;
    public static final SoundEvent ENTITY_GENERIC_DRINK;
    public static final SoundEvent ENTITY_GENERIC_EAT;
    public static final SoundEvent ENTITY_GENERIC_EXPLODE;
    public static final SoundEvent ENTITY_GENERIC_EXTINGUISH_FIRE;
    public static final SoundEvent ENTITY_GENERIC_HURT;
    public static final SoundEvent ENTITY_GENERIC_SMALL_FALL;
    public static final SoundEvent ENTITY_GENERIC_SPLASH;
    public static final SoundEvent ENTITY_GENERIC_SWIM;
    public static final SoundEvent ENTITY_GHAST_AMBIENT;
    public static final SoundEvent ENTITY_GHAST_DEATH;
    public static final SoundEvent ENTITY_GHAST_HURT;
    public static final SoundEvent ENTITY_GHAST_SCREAM;
    public static final SoundEvent ENTITY_GHAST_SHOOT;
    public static final SoundEvent ENTITY_GHAST_WARN;
    public static final SoundEvent BLOCK_GLASS_BREAK;
    public static final SoundEvent BLOCK_GLASS_FALL;
    public static final SoundEvent BLOCK_GLASS_HIT;
    public static final SoundEvent BLOCK_GLASS_PLACE;
    public static final SoundEvent BLOCK_GLASS_STEP;
    public static final SoundEvent BLOCK_GRASS_BREAK;
    public static final SoundEvent BLOCK_GRASS_FALL;
    public static final SoundEvent BLOCK_GRASS_HIT;
    public static final SoundEvent BLOCK_GRASS_PLACE;
    public static final SoundEvent BLOCK_GRASS_STEP;
    public static final SoundEvent BLOCK_GRAVEL_BREAK;
    public static final SoundEvent BLOCK_GRAVEL_FALL;
    public static final SoundEvent BLOCK_GRAVEL_HIT;
    public static final SoundEvent BLOCK_GRAVEL_PLACE;
    public static final SoundEvent BLOCK_GRAVEL_STEP;
    public static final SoundEvent ENTITY_GUARDIAN_AMBIENT;
    public static final SoundEvent ENTITY_GUARDIAN_AMBIENT_LAND;
    public static final SoundEvent ENTITY_GUARDIAN_ATTACK;
    public static final SoundEvent ENTITY_GUARDIAN_DEATH;
    public static final SoundEvent ENTITY_GUARDIAN_DEATH_LAND;
    public static final SoundEvent ENTITY_GUARDIAN_FLOP;
    public static final SoundEvent ENTITY_GUARDIAN_HURT;
    public static final SoundEvent ENTITY_GUARDIAN_HURT_LAND;
    public static final SoundEvent ITEM_HOE_TILL;
    public static final SoundEvent ENTITY_HORSE_AMBIENT;
    public static final SoundEvent ENTITY_HORSE_ANGRY;
    public static final SoundEvent ENTITY_HORSE_ARMOR;
    public static final SoundEvent ENTITY_HORSE_BREATHE;
    public static final SoundEvent ENTITY_HORSE_DEATH;
    public static final SoundEvent ENTITY_HORSE_EAT;
    public static final SoundEvent ENTITY_HORSE_GALLOP;
    public static final SoundEvent ENTITY_HORSE_HURT;
    public static final SoundEvent ENTITY_HORSE_JUMP;
    public static final SoundEvent ENTITY_HORSE_LAND;
    public static final SoundEvent ENTITY_HORSE_SADDLE;
    public static final SoundEvent ENTITY_HORSE_STEP;
    public static final SoundEvent ENTITY_HORSE_STEP_WOOD;
    public static final SoundEvent ENTITY_HOSTILE_BIG_FALL;
    public static final SoundEvent ENTITY_HOSTILE_DEATH;
    public static final SoundEvent ENTITY_HOSTILE_HURT;
    public static final SoundEvent ENTITY_HOSTILE_SMALL_FALL;
    public static final SoundEvent ENTITY_HOSTILE_SPLASH;
    public static final SoundEvent ENTITY_HOSTILE_SWIM;
    public static final SoundEvent ENTITY_HUSK_AMBIENT;
    public static final SoundEvent ENTITY_HUSK_DEATH;
    public static final SoundEvent ENTITY_HUSK_HURT;
    public static final SoundEvent ENTITY_HUSK_STEP;
    public static final SoundEvent ENTITY_ILLUSION_ILLAGER_AMBIENT;
    public static final SoundEvent ENTITY_ILLAGER_CAST_SPELL;
    public static final SoundEvent ENTITY_ILLAGER_DEATH;
    public static final SoundEvent ENTITY_ILLUSION_ILLAGER_HURT;
    public static final SoundEvent ENTITY_ILLAGER_MIRROR_MOVE;
    public static final SoundEvent ENTITY_ILLAGER_PREPARE_BLINDNESS;
    public static final SoundEvent ENTITY_ILLAGER_PREPARE_MIRROR;
    public static final SoundEvent ENTITY_IRONGOLEM_ATTACK;
    public static final SoundEvent ENTITY_IRONGOLEM_DEATH;
    public static final SoundEvent ENTITY_IRONGOLEM_HURT;
    public static final SoundEvent ENTITY_IRONGOLEM_STEP;
    public static final SoundEvent BLOCK_IRON_DOOR_CLOSE;
    public static final SoundEvent BLOCK_IRON_DOOR_OPEN;
    public static final SoundEvent BLOCK_IRON_TRAPDOOR_CLOSE;
    public static final SoundEvent BLOCK_IRON_TRAPDOOR_OPEN;
    public static final SoundEvent ENTITY_ITEMFRAME_ADD_ITEM;
    public static final SoundEvent ENTITY_ITEMFRAME_BREAK;
    public static final SoundEvent ENTITY_ITEMFRAME_PLACE;
    public static final SoundEvent ENTITY_ITEMFRAME_REMOVE_ITEM;
    public static final SoundEvent ENTITY_ITEMFRAME_ROTATE_ITEM;
    public static final SoundEvent ENTITY_ITEM_BREAK;
    public static final SoundEvent ENTITY_ITEM_PICKUP;
    public static final SoundEvent BLOCK_LADDER_BREAK;
    public static final SoundEvent BLOCK_LADDER_FALL;
    public static final SoundEvent BLOCK_LADDER_HIT;
    public static final SoundEvent BLOCK_LADDER_PLACE;
    public static final SoundEvent BLOCK_LADDER_STEP;
    public static final SoundEvent BLOCK_LAVA_AMBIENT;
    public static final SoundEvent BLOCK_LAVA_EXTINGUISH;
    public static final SoundEvent BLOCK_LAVA_POP;
    public static final SoundEvent ENTITY_LEASHKNOT_BREAK;
    public static final SoundEvent ENTITY_LEASHKNOT_PLACE;
    public static final SoundEvent BLOCK_LEVER_CLICK;
    public static final SoundEvent ENTITY_LIGHTNING_IMPACT;
    public static final SoundEvent ENTITY_LIGHTNING_THUNDER;
    public static final SoundEvent ENTITY_LINGERINGPOTION_THROW;
    public static final SoundEvent ENTITY_LLAMA_AMBIENT;
    public static final SoundEvent ENTITY_LLAMA_ANGRY;
    public static final SoundEvent ENTITY_LLAMA_CHEST;
    public static final SoundEvent ENTITY_LLAMA_DEATH;
    public static final SoundEvent ENTITY_LLAMA_EAT;
    public static final SoundEvent ENTITY_LLAMA_HURT;
    public static final SoundEvent ENTITY_LLAMA_SPIT;
    public static final SoundEvent ENTITY_LLAMA_STEP;
    public static final SoundEvent ENTITY_LLAMA_SWAG;
    public static final SoundEvent ENTITY_MAGMACUBE_DEATH;
    public static final SoundEvent ENTITY_MAGMACUBE_HURT;
    public static final SoundEvent ENTITY_MAGMACUBE_JUMP;
    public static final SoundEvent ENTITY_MAGMACUBE_SQUISH;
    public static final SoundEvent BLOCK_METAL_BREAK;
    public static final SoundEvent BLOCK_METAL_FALL;
    public static final SoundEvent BLOCK_METAL_HIT;
    public static final SoundEvent BLOCK_METAL_PLACE;
    public static final SoundEvent BLOCK_METAL_PRESSPLATE_CLICK_OFF;
    public static final SoundEvent BLOCK_METAL_PRESSPLATE_CLICK_ON;
    public static final SoundEvent BLOCK_METAL_STEP;
    public static final SoundEvent ENTITY_MINECART_INSIDE;
    public static final SoundEvent ENTITY_MINECART_RIDING;
    public static final SoundEvent ENTITY_MOOSHROOM_SHEAR;
    public static final SoundEvent ENTITY_MULE_AMBIENT;
    public static final SoundEvent ENTITY_MULE_CHEST;
    public static final SoundEvent ENTITY_MULE_DEATH;
    public static final SoundEvent ENTITY_MULE_HURT;
    public static final SoundEvent MUSIC_CREATIVE;
    public static final SoundEvent MUSIC_CREDITS;
    public static final SoundEvent MUSIC_DRAGON;
    public static final SoundEvent MUSIC_END;
    public static final SoundEvent MUSIC_GAME;
    public static final SoundEvent MUSIC_MENU;
    public static final SoundEvent MUSIC_NETHER;
    public static final SoundEvent BLOCK_NOTE_BASEDRUM;
    public static final SoundEvent BLOCK_NOTE_BASS;
    public static final SoundEvent BLOCK_NOTE_BELL;
    public static final SoundEvent BLOCK_NOTE_CHIME;
    public static final SoundEvent BLOCK_NOTE_FLUTE;
    public static final SoundEvent BLOCK_NOTE_GUITAR;
    public static final SoundEvent BLOCK_NOTE_HARP;
    public static final SoundEvent BLOCK_NOTE_HAT;
    public static final SoundEvent BLOCK_NOTE_PLING;
    public static final SoundEvent BLOCK_NOTE_SNARE;
    public static final SoundEvent BLOCK_NOTE_XYLOPHONE;
    public static final SoundEvent ENTITY_PAINTING_BREAK;
    public static final SoundEvent ENTITY_PAINTING_PLACE;
    public static final SoundEvent ENTITY_PARROT_AMBIENT;
    public static final SoundEvent ENTITY_PARROT_DEATH;
    public static final SoundEvent ENTITY_PARROT_EAT;
    public static final SoundEvent ENTITY_PARROT_FLY;
    public static final SoundEvent ENTITY_PARROT_HURT;
    public static final SoundEvent E_PARROT_IM_BLAZE;
    public static final SoundEvent E_PARROT_IM_CREEPER;
    public static final SoundEvent E_PARROT_IM_ELDER_GUARDIAN;
    public static final SoundEvent E_PARROT_IM_ENDERDRAGON;
    public static final SoundEvent E_PARROT_IM_ENDERMAN;
    public static final SoundEvent E_PARROT_IM_ENDERMITE;
    public static final SoundEvent E_PARROT_IM_EVOCATION_ILLAGER;
    public static final SoundEvent E_PARROT_IM_GHAST;
    public static final SoundEvent E_PARROT_IM_HUSK;
    public static final SoundEvent E_PARROT_IM_ILLUSION_ILLAGER;
    public static final SoundEvent E_PARROT_IM_MAGMACUBE;
    public static final SoundEvent E_PARROT_IM_POLAR_BEAR;
    public static final SoundEvent E_PARROT_IM_SHULKER;
    public static final SoundEvent E_PARROT_IM_SILVERFISH;
    public static final SoundEvent E_PARROT_IM_SKELETON;
    public static final SoundEvent E_PARROT_IM_SLIME;
    public static final SoundEvent E_PARROT_IM_SPIDER;
    public static final SoundEvent E_PARROT_IM_STRAY;
    public static final SoundEvent E_PARROT_IM_VEX;
    public static final SoundEvent E_PARROT_IM_VINDICATION_ILLAGER;
    public static final SoundEvent E_PARROT_IM_WITCH;
    public static final SoundEvent E_PARROT_IM_WITHER;
    public static final SoundEvent E_PARROT_IM_WITHER_SKELETON;
    public static final SoundEvent E_PARROT_IM_WOLF;
    public static final SoundEvent E_PARROT_IM_ZOMBIE;
    public static final SoundEvent E_PARROT_IM_ZOMBIE_PIGMAN;
    public static final SoundEvent E_PARROT_IM_ZOMBIE_VILLAGER;
    public static final SoundEvent ENTITY_PARROT_STEP;
    public static final SoundEvent ENTITY_PIG_AMBIENT;
    public static final SoundEvent ENTITY_PIG_DEATH;
    public static final SoundEvent ENTITY_PIG_HURT;
    public static final SoundEvent ENTITY_PIG_SADDLE;
    public static final SoundEvent ENTITY_PIG_STEP;
    public static final SoundEvent BLOCK_PISTON_CONTRACT;
    public static final SoundEvent BLOCK_PISTON_EXTEND;
    public static final SoundEvent ENTITY_PLAYER_ATTACK_CRIT;
    public static final SoundEvent ENTITY_PLAYER_ATTACK_KNOCKBACK;
    public static final SoundEvent ENTITY_PLAYER_ATTACK_NODAMAGE;
    public static final SoundEvent ENTITY_PLAYER_ATTACK_STRONG;
    public static final SoundEvent ENTITY_PLAYER_ATTACK_SWEEP;
    public static final SoundEvent ENTITY_PLAYER_ATTACK_WEAK;
    public static final SoundEvent ENTITY_PLAYER_BIG_FALL;
    public static final SoundEvent ENTITY_PLAYER_BREATH;
    public static final SoundEvent ENTITY_PLAYER_BURP;
    public static final SoundEvent ENTITY_PLAYER_DEATH;
    public static final SoundEvent ENTITY_PLAYER_HURT;
    public static final SoundEvent ENTITY_PLAYER_HURT_DROWN;
    public static final SoundEvent ENTITY_PLAYER_HURT_ON_FIRE;
    public static final SoundEvent ENTITY_PLAYER_LEVELUP;
    public static final SoundEvent ENTITY_PLAYER_SMALL_FALL;
    public static final SoundEvent ENTITY_PLAYER_SPLASH;
    public static final SoundEvent ENTITY_PLAYER_SWIM;
    public static final SoundEvent ENTITY_POLAR_BEAR_AMBIENT;
    public static final SoundEvent ENTITY_POLAR_BEAR_BABY_AMBIENT;
    public static final SoundEvent ENTITY_POLAR_BEAR_DEATH;
    public static final SoundEvent ENTITY_POLAR_BEAR_HURT;
    public static final SoundEvent ENTITY_POLAR_BEAR_STEP;
    public static final SoundEvent ENTITY_POLAR_BEAR_WARNING;
    public static final SoundEvent BLOCK_PORTAL_AMBIENT;
    public static final SoundEvent BLOCK_PORTAL_TRAVEL;
    public static final SoundEvent BLOCK_PORTAL_TRIGGER;
    public static final SoundEvent ENTITY_RABBIT_AMBIENT;
    public static final SoundEvent ENTITY_RABBIT_ATTACK;
    public static final SoundEvent ENTITY_RABBIT_DEATH;
    public static final SoundEvent ENTITY_RABBIT_HURT;
    public static final SoundEvent ENTITY_RABBIT_JUMP;
    public static final SoundEvent RECORD_11;
    public static final SoundEvent RECORD_13;
    public static final SoundEvent RECORD_BLOCKS;
    public static final SoundEvent RECORD_CAT;
    public static final SoundEvent RECORD_CHIRP;
    public static final SoundEvent RECORD_FAR;
    public static final SoundEvent RECORD_MALL;
    public static final SoundEvent RECORD_MELLOHI;
    public static final SoundEvent RECORD_STAL;
    public static final SoundEvent RECORD_STRAD;
    public static final SoundEvent RECORD_WAIT;
    public static final SoundEvent RECORD_WARD;
    public static final SoundEvent BLOCK_REDSTONE_TORCH_BURNOUT;
    public static final SoundEvent BLOCK_SAND_BREAK;
    public static final SoundEvent BLOCK_SAND_FALL;
    public static final SoundEvent BLOCK_SAND_HIT;
    public static final SoundEvent BLOCK_SAND_PLACE;
    public static final SoundEvent BLOCK_SAND_STEP;
    public static final SoundEvent ENTITY_SHEEP_AMBIENT;
    public static final SoundEvent ENTITY_SHEEP_DEATH;
    public static final SoundEvent ENTITY_SHEEP_HURT;
    public static final SoundEvent ENTITY_SHEEP_SHEAR;
    public static final SoundEvent ENTITY_SHEEP_STEP;
    public static final SoundEvent ITEM_SHIELD_BLOCK;
    public static final SoundEvent ITEM_SHIELD_BREAK;
    public static final SoundEvent ITEM_SHOVEL_FLATTEN;
    public static final SoundEvent ENTITY_SHULKER_AMBIENT;
    public static final SoundEvent BLOCK_SHULKER_BOX_CLOSE;
    public static final SoundEvent BLOCK_SHULKER_BOX_OPEN;
    public static final SoundEvent ENTITY_SHULKER_BULLET_HIT;
    public static final SoundEvent ENTITY_SHULKER_BULLET_HURT;
    public static final SoundEvent ENTITY_SHULKER_CLOSE;
    public static final SoundEvent ENTITY_SHULKER_DEATH;
    public static final SoundEvent ENTITY_SHULKER_HURT;
    public static final SoundEvent ENTITY_SHULKER_HURT_CLOSED;
    public static final SoundEvent ENTITY_SHULKER_OPEN;
    public static final SoundEvent ENTITY_SHULKER_SHOOT;
    public static final SoundEvent ENTITY_SHULKER_TELEPORT;
    public static final SoundEvent ENTITY_SILVERFISH_AMBIENT;
    public static final SoundEvent ENTITY_SILVERFISH_DEATH;
    public static final SoundEvent ENTITY_SILVERFISH_HURT;
    public static final SoundEvent ENTITY_SILVERFISH_STEP;
    public static final SoundEvent ENTITY_SKELETON_AMBIENT;
    public static final SoundEvent ENTITY_SKELETON_DEATH;
    public static final SoundEvent ENTITY_SKELETON_HORSE_AMBIENT;
    public static final SoundEvent ENTITY_SKELETON_HORSE_DEATH;
    public static final SoundEvent ENTITY_SKELETON_HORSE_HURT;
    public static final SoundEvent ENTITY_SKELETON_HURT;
    public static final SoundEvent ENTITY_SKELETON_SHOOT;
    public static final SoundEvent ENTITY_SKELETON_STEP;
    public static final SoundEvent ENTITY_SLIME_ATTACK;
    public static final SoundEvent BLOCK_SLIME_BREAK;
    public static final SoundEvent ENTITY_SLIME_DEATH;
    public static final SoundEvent BLOCK_SLIME_FALL;
    public static final SoundEvent BLOCK_SLIME_HIT;
    public static final SoundEvent ENTITY_SLIME_HURT;
    public static final SoundEvent ENTITY_SLIME_JUMP;
    public static final SoundEvent BLOCK_SLIME_PLACE;
    public static final SoundEvent ENTITY_SLIME_SQUISH;
    public static final SoundEvent BLOCK_SLIME_STEP;
    public static final SoundEvent ENTITY_SMALL_MAGMACUBE_DEATH;
    public static final SoundEvent ENTITY_SMALL_MAGMACUBE_HURT;
    public static final SoundEvent ENTITY_SMALL_MAGMACUBE_SQUISH;
    public static final SoundEvent ENTITY_SMALL_SLIME_DEATH;
    public static final SoundEvent ENTITY_SMALL_SLIME_HURT;
    public static final SoundEvent ENTITY_SMALL_SLIME_JUMP;
    public static final SoundEvent ENTITY_SMALL_SLIME_SQUISH;
    public static final SoundEvent ENTITY_SNOWBALL_THROW;
    public static final SoundEvent ENTITY_SNOWMAN_AMBIENT;
    public static final SoundEvent ENTITY_SNOWMAN_DEATH;
    public static final SoundEvent ENTITY_SNOWMAN_HURT;
    public static final SoundEvent ENTITY_SNOWMAN_SHOOT;
    public static final SoundEvent BLOCK_SNOW_BREAK;
    public static final SoundEvent BLOCK_SNOW_FALL;
    public static final SoundEvent BLOCK_SNOW_HIT;
    public static final SoundEvent BLOCK_SNOW_PLACE;
    public static final SoundEvent BLOCK_SNOW_STEP;
    public static final SoundEvent ENTITY_SPIDER_AMBIENT;
    public static final SoundEvent ENTITY_SPIDER_DEATH;
    public static final SoundEvent ENTITY_SPIDER_HURT;
    public static final SoundEvent ENTITY_SPIDER_STEP;
    public static final SoundEvent ENTITY_SPLASH_POTION_BREAK;
    public static final SoundEvent ENTITY_SPLASH_POTION_THROW;
    public static final SoundEvent ENTITY_SQUID_AMBIENT;
    public static final SoundEvent ENTITY_SQUID_DEATH;
    public static final SoundEvent ENTITY_SQUID_HURT;
    public static final SoundEvent BLOCK_STONE_BREAK;
    public static final SoundEvent BLOCK_STONE_BUTTON_CLICK_OFF;
    public static final SoundEvent BLOCK_STONE_BUTTON_CLICK_ON;
    public static final SoundEvent BLOCK_STONE_FALL;
    public static final SoundEvent BLOCK_STONE_HIT;
    public static final SoundEvent BLOCK_STONE_PLACE;
    public static final SoundEvent BLOCK_STONE_PRESSPLATE_CLICK_OFF;
    public static final SoundEvent BLOCK_STONE_PRESSPLATE_CLICK_ON;
    public static final SoundEvent BLOCK_STONE_STEP;
    public static final SoundEvent ENTITY_STRAY_AMBIENT;
    public static final SoundEvent ENTITY_STRAY_DEATH;
    public static final SoundEvent ENTITY_STRAY_HURT;
    public static final SoundEvent ENTITY_STRAY_STEP;
    public static final SoundEvent ENCHANT_THORNS_HIT;
    public static final SoundEvent ENTITY_TNT_PRIMED;
    public static final SoundEvent ITEM_TOTEM_USE;
    public static final SoundEvent BLOCK_TRIPWIRE_ATTACH;
    public static final SoundEvent BLOCK_TRIPWIRE_CLICK_OFF;
    public static final SoundEvent BLOCK_TRIPWIRE_CLICK_ON;
    public static final SoundEvent BLOCK_TRIPWIRE_DETACH;
    public static final SoundEvent UI_BUTTON_CLICK;
    public static final SoundEvent UI_TOAST_IN;
    public static final SoundEvent UI_TOAST_OUT;
    public static final SoundEvent UI_TOAST_CHALLENGE_COMPLETE;
    public static final SoundEvent ENTITY_VEX_AMBIENT;
    public static final SoundEvent ENTITY_VEX_CHARGE;
    public static final SoundEvent ENTITY_VEX_DEATH;
    public static final SoundEvent ENTITY_VEX_HURT;
    public static final SoundEvent ENTITY_VILLAGER_AMBIENT;
    public static final SoundEvent ENTITY_VILLAGER_DEATH;
    public static final SoundEvent ENTITY_VILLAGER_HURT;
    public static final SoundEvent ENTITY_VILLAGER_NO;
    public static final SoundEvent ENTITY_VILLAGER_TRADING;
    public static final SoundEvent ENTITY_VILLAGER_YES;
    public static final SoundEvent VINDICATION_ILLAGER_AMBIENT;
    public static final SoundEvent VINDICATION_ILLAGER_DEATH;
    public static final SoundEvent ENTITY_VINDICATION_ILLAGER_HURT;
    public static final SoundEvent BLOCK_WATERLILY_PLACE;
    public static final SoundEvent BLOCK_WATER_AMBIENT;
    public static final SoundEvent WEATHER_RAIN;
    public static final SoundEvent WEATHER_RAIN_ABOVE;
    public static final SoundEvent ENTITY_WITCH_AMBIENT;
    public static final SoundEvent ENTITY_WITCH_DEATH;
    public static final SoundEvent ENTITY_WITCH_DRINK;
    public static final SoundEvent ENTITY_WITCH_HURT;
    public static final SoundEvent ENTITY_WITCH_THROW;
    public static final SoundEvent ENTITY_WITHER_AMBIENT;
    public static final SoundEvent ENTITY_WITHER_BREAK_BLOCK;
    public static final SoundEvent ENTITY_WITHER_DEATH;
    public static final SoundEvent ENTITY_WITHER_HURT;
    public static final SoundEvent ENTITY_WITHER_SHOOT;
    public static final SoundEvent ENTITY_WITHER_SKELETON_AMBIENT;
    public static final SoundEvent ENTITY_WITHER_SKELETON_DEATH;
    public static final SoundEvent ENTITY_WITHER_SKELETON_HURT;
    public static final SoundEvent ENTITY_WITHER_SKELETON_STEP;
    public static final SoundEvent ENTITY_WITHER_SPAWN;
    public static final SoundEvent ENTITY_WOLF_AMBIENT;
    public static final SoundEvent ENTITY_WOLF_DEATH;
    public static final SoundEvent ENTITY_WOLF_GROWL;
    public static final SoundEvent ENTITY_WOLF_HOWL;
    public static final SoundEvent ENTITY_WOLF_HURT;
    public static final SoundEvent ENTITY_WOLF_PANT;
    public static final SoundEvent ENTITY_WOLF_SHAKE;
    public static final SoundEvent ENTITY_WOLF_STEP;
    public static final SoundEvent ENTITY_WOLF_WHINE;
    public static final SoundEvent BLOCK_WOODEN_DOOR_CLOSE;
    public static final SoundEvent BLOCK_WOODEN_DOOR_OPEN;
    public static final SoundEvent BLOCK_WOODEN_TRAPDOOR_CLOSE;
    public static final SoundEvent BLOCK_WOODEN_TRAPDOOR_OPEN;
    public static final SoundEvent BLOCK_WOOD_BREAK;
    public static final SoundEvent BLOCK_WOOD_BUTTON_CLICK_OFF;
    public static final SoundEvent BLOCK_WOOD_BUTTON_CLICK_ON;
    public static final SoundEvent BLOCK_WOOD_FALL;
    public static final SoundEvent BLOCK_WOOD_HIT;
    public static final SoundEvent BLOCK_WOOD_PLACE;
    public static final SoundEvent BLOCK_WOOD_PRESSPLATE_CLICK_OFF;
    public static final SoundEvent BLOCK_WOOD_PRESSPLATE_CLICK_ON;
    public static final SoundEvent BLOCK_WOOD_STEP;
    public static final SoundEvent ENTITY_ZOMBIE_AMBIENT;
    public static final SoundEvent ENTITY_ZOMBIE_ATTACK_DOOR_WOOD;
    public static final SoundEvent ENTITY_ZOMBIE_ATTACK_IRON_DOOR;
    public static final SoundEvent ENTITY_ZOMBIE_BREAK_DOOR_WOOD;
    public static final SoundEvent ENTITY_ZOMBIE_DEATH;
    public static final SoundEvent ENTITY_ZOMBIE_HORSE_AMBIENT;
    public static final SoundEvent ENTITY_ZOMBIE_HORSE_DEATH;
    public static final SoundEvent ENTITY_ZOMBIE_HORSE_HURT;
    public static final SoundEvent ENTITY_ZOMBIE_HURT;
    public static final SoundEvent ENTITY_ZOMBIE_INFECT;
    public static final SoundEvent ENTITY_ZOMBIE_PIG_AMBIENT;
    public static final SoundEvent ENTITY_ZOMBIE_PIG_ANGRY;
    public static final SoundEvent ENTITY_ZOMBIE_PIG_DEATH;
    public static final SoundEvent ENTITY_ZOMBIE_PIG_HURT;
    public static final SoundEvent ENTITY_ZOMBIE_STEP;
    public static final SoundEvent ENTITY_ZOMBIE_VILLAGER_AMBIENT;
    public static final SoundEvent ENTITY_ZOMBIE_VILLAGER_CONVERTED;
    public static final SoundEvent ENTITY_ZOMBIE_VILLAGER_CURE;
    public static final SoundEvent ENTITY_ZOMBIE_VILLAGER_DEATH;
    public static final SoundEvent ENTITY_ZOMBIE_VILLAGER_HURT;
    public static final SoundEvent ENTITY_ZOMBIE_VILLAGER_STEP;
    
    private SoundEvents() {
    }
    
    static {
        AMBIENT_CAVE = SideEffects.objectValue();
        BLOCK_ANVIL_BREAK = SideEffects.objectValue();
        BLOCK_ANVIL_DESTROY = SideEffects.objectValue();
        BLOCK_ANVIL_FALL = SideEffects.objectValue();
        BLOCK_ANVIL_HIT = SideEffects.objectValue();
        BLOCK_ANVIL_LAND = SideEffects.objectValue();
        BLOCK_ANVIL_PLACE = SideEffects.objectValue();
        BLOCK_ANVIL_STEP = SideEffects.objectValue();
        BLOCK_ANVIL_USE = SideEffects.objectValue();
        ENTITY_ARMORSTAND_BREAK = SideEffects.objectValue();
        ENTITY_ARMORSTAND_FALL = SideEffects.objectValue();
        ENTITY_ARMORSTAND_HIT = SideEffects.objectValue();
        ENTITY_ARMORSTAND_PLACE = SideEffects.objectValue();
        ITEM_ARMOR_EQUIP_CHAIN = SideEffects.objectValue();
        ITEM_ARMOR_EQUIP_DIAMOND = SideEffects.objectValue();
        ITEM_ARMOR_EQIIP_ELYTRA = SideEffects.objectValue();
        ITEM_ARMOR_EQUIP_GENERIC = SideEffects.objectValue();
        ITEM_ARMOR_EQUIP_GOLD = SideEffects.objectValue();
        ITEM_ARMOR_EQUIP_IRON = SideEffects.objectValue();
        ITEM_ARMOR_EQUIP_LEATHER = SideEffects.objectValue();
        ENTITY_ARROW_HIT = SideEffects.objectValue();
        ENTITY_ARROW_HIT_PLAYER = SideEffects.objectValue();
        ENTITY_ARROW_SHOOT = SideEffects.objectValue();
        ENTITY_BAT_AMBIENT = SideEffects.objectValue();
        ENTITY_BAT_DEATH = SideEffects.objectValue();
        ENTITY_BAT_HURT = SideEffects.objectValue();
        ENTITY_BAT_LOOP = SideEffects.objectValue();
        ENTITY_BAT_TAKEOFF = SideEffects.objectValue();
        ENTITY_BLAZE_AMBIENT = SideEffects.objectValue();
        ENTITY_BLAZE_BURN = SideEffects.objectValue();
        ENTITY_BLAZE_DEATH = SideEffects.objectValue();
        ENTITY_BLAZE_HURT = SideEffects.objectValue();
        ENTITY_BLAZE_SHOOT = SideEffects.objectValue();
        ENTITY_BOAT_PADDLE_LAND = SideEffects.objectValue();
        ENTITY_BOAT_PADDLE_WATER = SideEffects.objectValue();
        ENTITY_BOBBER_RETRIEVE = SideEffects.objectValue();
        ENTITY_BOBBER_SPLASH = SideEffects.objectValue();
        ENTITY_BOBBER_THROW = SideEffects.objectValue();
        ITEM_BOTTLE_EMPTY = SideEffects.objectValue();
        ITEM_BOTTLE_FILL = SideEffects.objectValue();
        ITEM_BOTTLE_FILL_DRAGONBREATH = SideEffects.objectValue();
        BLOCK_BREWING_STAND_BREW = SideEffects.objectValue();
        ITEM_BUCKET_EMPTY = SideEffects.objectValue();
        ITEM_BUCKET_EMPTY_LAVA = SideEffects.objectValue();
        ITEM_BUCKET_FILL = SideEffects.objectValue();
        ITEM_BUCKET_FILL_LAVA = SideEffects.objectValue();
        ENTITY_CAT_AMBIENT = SideEffects.objectValue();
        ENTITY_CAT_DEATH = SideEffects.objectValue();
        ENTITY_CAT_HISS = SideEffects.objectValue();
        ENTITY_CAT_HURT = SideEffects.objectValue();
        ENTITY_CAT_PURR = SideEffects.objectValue();
        ENTITY_CAT_PURREOW = SideEffects.objectValue();
        BLOCK_CHEST_CLOSE = SideEffects.objectValue();
        BLOCK_CHEST_LOCKED = SideEffects.objectValue();
        BLOCK_CHEST_OPEN = SideEffects.objectValue();
        ENTITY_CHICKEN_AMBIENT = SideEffects.objectValue();
        ENTITY_CHICKEN_DEATH = SideEffects.objectValue();
        ENTITY_CHICKEN_EGG = SideEffects.objectValue();
        ENTITY_CHICKEN_HURT = SideEffects.objectValue();
        ENTITY_CHICKEN_STEP = SideEffects.objectValue();
        BLOCK_CHORUS_FLOWER_DEATH = SideEffects.objectValue();
        BLOCK_CHORUS_FLOWER_GROW = SideEffects.objectValue();
        ITEM_CHORUS_FRUIT_TELEPORT = SideEffects.objectValue();
        BLOCK_CLOTH_BREAK = SideEffects.objectValue();
        BLOCK_CLOTH_FALL = SideEffects.objectValue();
        BLOCK_CLOTH_HIT = SideEffects.objectValue();
        BLOCK_CLOTH_PLACE = SideEffects.objectValue();
        BLOCK_CLOTH_STEP = SideEffects.objectValue();
        BLOCK_COMPARATOR_CLICK = SideEffects.objectValue();
        ENTITY_COW_AMBIENT = SideEffects.objectValue();
        ENTITY_COW_DEATH = SideEffects.objectValue();
        ENTITY_COW_HURT = SideEffects.objectValue();
        ENTITY_COW_MILK = SideEffects.objectValue();
        ENTITY_COW_STEP = SideEffects.objectValue();
        ENTITY_CREEPER_DEATH = SideEffects.objectValue();
        ENTITY_CREEPER_HURT = SideEffects.objectValue();
        ENTITY_CREEPER_PRIMED = SideEffects.objectValue();
        BLOCK_DISPENSER_DISPENSE = SideEffects.objectValue();
        BLOCK_DISPENSER_FAIL = SideEffects.objectValue();
        BLOCK_DISPENSER_LAUNCH = SideEffects.objectValue();
        ENTITY_DONKEY_AMBIENT = SideEffects.objectValue();
        ENTITY_DONKEY_ANGRY = SideEffects.objectValue();
        ENTITY_DONKEY_CHEST = SideEffects.objectValue();
        ENTITY_DONKEY_DEATH = SideEffects.objectValue();
        ENTITY_DONKEY_HURT = SideEffects.objectValue();
        ENTITY_EGG_THROW = SideEffects.objectValue();
        ENTITY_ELDER_GUARDIAN_AMBIENT = SideEffects.objectValue();
        ENTITY_ELDERGUARDIAN_AMBIENTLAND = SideEffects.objectValue();
        ENTITY_ELDER_GUARDIAN_CURSE = SideEffects.objectValue();
        ENTITY_ELDER_GUARDIAN_DEATH = SideEffects.objectValue();
        ENTITY_ELDER_GUARDIAN_DEATH_LAND = SideEffects.objectValue();
        ENTITY_ELDER_GUARDIAN_FLOP = SideEffects.objectValue();
        ENTITY_ELDER_GUARDIAN_HURT = SideEffects.objectValue();
        ENTITY_ELDER_GUARDIAN_HURT_LAND = SideEffects.objectValue();
        ITEM_ELYTRA_FLYING = SideEffects.objectValue();
        BLOCK_ENCHANTMENT_TABLE_USE = SideEffects.objectValue();
        BLOCK_ENDERCHEST_CLOSE = SideEffects.objectValue();
        BLOCK_ENDERCHEST_OPEN = SideEffects.objectValue();
        ENTITY_ENDERDRAGON_AMBIENT = SideEffects.objectValue();
        ENTITY_ENDERDRAGON_DEATH = SideEffects.objectValue();
        ENTITY_ENDERDRAGON_FIREBALL_EPLD = SideEffects.objectValue();
        ENTITY_ENDERDRAGON_FLAP = SideEffects.objectValue();
        ENTITY_ENDERDRAGON_GROWL = SideEffects.objectValue();
        ENTITY_ENDERDRAGON_HURT = SideEffects.objectValue();
        ENTITY_ENDERDRAGON_SHOOT = SideEffects.objectValue();
        ENTITY_ENDEREYE_DEATH = SideEffects.objectValue();
        ENTITY_ENDEREYE_LAUNCH = SideEffects.objectValue();
        ENTITY_ENDERMEN_AMBIENT = SideEffects.objectValue();
        ENTITY_ENDERMEN_DEATH = SideEffects.objectValue();
        ENTITY_ENDERMEN_HURT = SideEffects.objectValue();
        ENTITY_ENDERMEN_SCREAM = SideEffects.objectValue();
        ENTITY_ENDERMEN_STARE = SideEffects.objectValue();
        ENTITY_ENDERMEN_TELEPORT = SideEffects.objectValue();
        ENTITY_ENDERMITE_AMBIENT = SideEffects.objectValue();
        ENTITY_ENDERMITE_DEATH = SideEffects.objectValue();
        ENTITY_ENDERMITE_HURT = SideEffects.objectValue();
        ENTITY_ENDERMITE_STEP = SideEffects.objectValue();
        ENTITY_ENDERPEARL_THROW = SideEffects.objectValue();
        BLOCK_END_GATEWAY_SPAWN = SideEffects.objectValue();
        BLOCK_END_PORTAL_FRAME_FILL = SideEffects.objectValue();
        BLOCK_END_PORTAL_SPAWN = SideEffects.objectValue();
        EVOCATION_FANGS_ATTACK = SideEffects.objectValue();
        ENTITY_EVOCATION_ILLAGER_AMBIENT = SideEffects.objectValue();
        EVOCATION_ILLAGER_CAST_SPELL = SideEffects.objectValue();
        EVOCATION_ILLAGER_DEATH = SideEffects.objectValue();
        ENTITY_EVOCATION_ILLAGER_HURT = SideEffects.objectValue();
        EVOCATION_ILLAGER_PREPARE_ATTACK = SideEffects.objectValue();
        EVOCATION_ILLAGER_PREPARE_SUMMON = SideEffects.objectValue();
        EVOCATION_ILLAGER_PREPARE_WOLOLO = SideEffects.objectValue();
        ENTITY_EXPERIENCE_BOTTLE_THROW = SideEffects.objectValue();
        ENTITY_EXPERIENCE_ORB_PICKUP = SideEffects.objectValue();
        BLOCK_FENCE_GATE_CLOSE = SideEffects.objectValue();
        BLOCK_FENCE_GATE_OPEN = SideEffects.objectValue();
        ITEM_FIRECHARGE_USE = SideEffects.objectValue();
        ENTITY_FIREWORK_BLAST = SideEffects.objectValue();
        ENTITY_FIREWORK_BLAST_FAR = SideEffects.objectValue();
        ENTITY_FIREWORK_LARGE_BLAST = SideEffects.objectValue();
        ENTITY_FIREWORK_LARGE_BLAST_FAR = SideEffects.objectValue();
        ENTITY_FIREWORK_LAUNCH = SideEffects.objectValue();
        ENTITY_FIREWORK_SHOOT = SideEffects.objectValue();
        ENTITY_FIREWORK_TWINKLE = SideEffects.objectValue();
        ENTITY_FIREWORK_TWINKLE_FAR = SideEffects.objectValue();
        BLOCK_FIRE_AMBIENT = SideEffects.objectValue();
        BLOCK_FIRE_EXTINGUISH = SideEffects.objectValue();
        ITEM_FLINTANDSTEEL_USE = SideEffects.objectValue();
        BLOCK_FURNACE_FIRE_CRACKLE = SideEffects.objectValue();
        ENTITY_GENERIC_BIG_FALL = SideEffects.objectValue();
        ENTITY_GENERIC_BURN = SideEffects.objectValue();
        ENTITY_GENERIC_DEATH = SideEffects.objectValue();
        ENTITY_GENERIC_DRINK = SideEffects.objectValue();
        ENTITY_GENERIC_EAT = SideEffects.objectValue();
        ENTITY_GENERIC_EXPLODE = SideEffects.objectValue();
        ENTITY_GENERIC_EXTINGUISH_FIRE = SideEffects.objectValue();
        ENTITY_GENERIC_HURT = SideEffects.objectValue();
        ENTITY_GENERIC_SMALL_FALL = SideEffects.objectValue();
        ENTITY_GENERIC_SPLASH = SideEffects.objectValue();
        ENTITY_GENERIC_SWIM = SideEffects.objectValue();
        ENTITY_GHAST_AMBIENT = SideEffects.objectValue();
        ENTITY_GHAST_DEATH = SideEffects.objectValue();
        ENTITY_GHAST_HURT = SideEffects.objectValue();
        ENTITY_GHAST_SCREAM = SideEffects.objectValue();
        ENTITY_GHAST_SHOOT = SideEffects.objectValue();
        ENTITY_GHAST_WARN = SideEffects.objectValue();
        BLOCK_GLASS_BREAK = SideEffects.objectValue();
        BLOCK_GLASS_FALL = SideEffects.objectValue();
        BLOCK_GLASS_HIT = SideEffects.objectValue();
        BLOCK_GLASS_PLACE = SideEffects.objectValue();
        BLOCK_GLASS_STEP = SideEffects.objectValue();
        BLOCK_GRASS_BREAK = SideEffects.objectValue();
        BLOCK_GRASS_FALL = SideEffects.objectValue();
        BLOCK_GRASS_HIT = SideEffects.objectValue();
        BLOCK_GRASS_PLACE = SideEffects.objectValue();
        BLOCK_GRASS_STEP = SideEffects.objectValue();
        BLOCK_GRAVEL_BREAK = SideEffects.objectValue();
        BLOCK_GRAVEL_FALL = SideEffects.objectValue();
        BLOCK_GRAVEL_HIT = SideEffects.objectValue();
        BLOCK_GRAVEL_PLACE = SideEffects.objectValue();
        BLOCK_GRAVEL_STEP = SideEffects.objectValue();
        ENTITY_GUARDIAN_AMBIENT = SideEffects.objectValue();
        ENTITY_GUARDIAN_AMBIENT_LAND = SideEffects.objectValue();
        ENTITY_GUARDIAN_ATTACK = SideEffects.objectValue();
        ENTITY_GUARDIAN_DEATH = SideEffects.objectValue();
        ENTITY_GUARDIAN_DEATH_LAND = SideEffects.objectValue();
        ENTITY_GUARDIAN_FLOP = SideEffects.objectValue();
        ENTITY_GUARDIAN_HURT = SideEffects.objectValue();
        ENTITY_GUARDIAN_HURT_LAND = SideEffects.objectValue();
        ITEM_HOE_TILL = SideEffects.objectValue();
        ENTITY_HORSE_AMBIENT = SideEffects.objectValue();
        ENTITY_HORSE_ANGRY = SideEffects.objectValue();
        ENTITY_HORSE_ARMOR = SideEffects.objectValue();
        ENTITY_HORSE_BREATHE = SideEffects.objectValue();
        ENTITY_HORSE_DEATH = SideEffects.objectValue();
        ENTITY_HORSE_EAT = SideEffects.objectValue();
        ENTITY_HORSE_GALLOP = SideEffects.objectValue();
        ENTITY_HORSE_HURT = SideEffects.objectValue();
        ENTITY_HORSE_JUMP = SideEffects.objectValue();
        ENTITY_HORSE_LAND = SideEffects.objectValue();
        ENTITY_HORSE_SADDLE = SideEffects.objectValue();
        ENTITY_HORSE_STEP = SideEffects.objectValue();
        ENTITY_HORSE_STEP_WOOD = SideEffects.objectValue();
        ENTITY_HOSTILE_BIG_FALL = SideEffects.objectValue();
        ENTITY_HOSTILE_DEATH = SideEffects.objectValue();
        ENTITY_HOSTILE_HURT = SideEffects.objectValue();
        ENTITY_HOSTILE_SMALL_FALL = SideEffects.objectValue();
        ENTITY_HOSTILE_SPLASH = SideEffects.objectValue();
        ENTITY_HOSTILE_SWIM = SideEffects.objectValue();
        ENTITY_HUSK_AMBIENT = SideEffects.objectValue();
        ENTITY_HUSK_DEATH = SideEffects.objectValue();
        ENTITY_HUSK_HURT = SideEffects.objectValue();
        ENTITY_HUSK_STEP = SideEffects.objectValue();
        ENTITY_ILLUSION_ILLAGER_AMBIENT = SideEffects.objectValue();
        ENTITY_ILLAGER_CAST_SPELL = SideEffects.objectValue();
        ENTITY_ILLAGER_DEATH = SideEffects.objectValue();
        ENTITY_ILLUSION_ILLAGER_HURT = SideEffects.objectValue();
        ENTITY_ILLAGER_MIRROR_MOVE = SideEffects.objectValue();
        ENTITY_ILLAGER_PREPARE_BLINDNESS = SideEffects.objectValue();
        ENTITY_ILLAGER_PREPARE_MIRROR = SideEffects.objectValue();
        ENTITY_IRONGOLEM_ATTACK = SideEffects.objectValue();
        ENTITY_IRONGOLEM_DEATH = SideEffects.objectValue();
        ENTITY_IRONGOLEM_HURT = SideEffects.objectValue();
        ENTITY_IRONGOLEM_STEP = SideEffects.objectValue();
        BLOCK_IRON_DOOR_CLOSE = SideEffects.objectValue();
        BLOCK_IRON_DOOR_OPEN = SideEffects.objectValue();
        BLOCK_IRON_TRAPDOOR_CLOSE = SideEffects.objectValue();
        BLOCK_IRON_TRAPDOOR_OPEN = SideEffects.objectValue();
        ENTITY_ITEMFRAME_ADD_ITEM = SideEffects.objectValue();
        ENTITY_ITEMFRAME_BREAK = SideEffects.objectValue();
        ENTITY_ITEMFRAME_PLACE = SideEffects.objectValue();
        ENTITY_ITEMFRAME_REMOVE_ITEM = SideEffects.objectValue();
        ENTITY_ITEMFRAME_ROTATE_ITEM = SideEffects.objectValue();
        ENTITY_ITEM_BREAK = SideEffects.objectValue();
        ENTITY_ITEM_PICKUP = SideEffects.objectValue();
        BLOCK_LADDER_BREAK = SideEffects.objectValue();
        BLOCK_LADDER_FALL = SideEffects.objectValue();
        BLOCK_LADDER_HIT = SideEffects.objectValue();
        BLOCK_LADDER_PLACE = SideEffects.objectValue();
        BLOCK_LADDER_STEP = SideEffects.objectValue();
        BLOCK_LAVA_AMBIENT = SideEffects.objectValue();
        BLOCK_LAVA_EXTINGUISH = SideEffects.objectValue();
        BLOCK_LAVA_POP = SideEffects.objectValue();
        ENTITY_LEASHKNOT_BREAK = SideEffects.objectValue();
        ENTITY_LEASHKNOT_PLACE = SideEffects.objectValue();
        BLOCK_LEVER_CLICK = SideEffects.objectValue();
        ENTITY_LIGHTNING_IMPACT = SideEffects.objectValue();
        ENTITY_LIGHTNING_THUNDER = SideEffects.objectValue();
        ENTITY_LINGERINGPOTION_THROW = SideEffects.objectValue();
        ENTITY_LLAMA_AMBIENT = SideEffects.objectValue();
        ENTITY_LLAMA_ANGRY = SideEffects.objectValue();
        ENTITY_LLAMA_CHEST = SideEffects.objectValue();
        ENTITY_LLAMA_DEATH = SideEffects.objectValue();
        ENTITY_LLAMA_EAT = SideEffects.objectValue();
        ENTITY_LLAMA_HURT = SideEffects.objectValue();
        ENTITY_LLAMA_SPIT = SideEffects.objectValue();
        ENTITY_LLAMA_STEP = SideEffects.objectValue();
        ENTITY_LLAMA_SWAG = SideEffects.objectValue();
        ENTITY_MAGMACUBE_DEATH = SideEffects.objectValue();
        ENTITY_MAGMACUBE_HURT = SideEffects.objectValue();
        ENTITY_MAGMACUBE_JUMP = SideEffects.objectValue();
        ENTITY_MAGMACUBE_SQUISH = SideEffects.objectValue();
        BLOCK_METAL_BREAK = SideEffects.objectValue();
        BLOCK_METAL_FALL = SideEffects.objectValue();
        BLOCK_METAL_HIT = SideEffects.objectValue();
        BLOCK_METAL_PLACE = SideEffects.objectValue();
        BLOCK_METAL_PRESSPLATE_CLICK_OFF = SideEffects.objectValue();
        BLOCK_METAL_PRESSPLATE_CLICK_ON = SideEffects.objectValue();
        BLOCK_METAL_STEP = SideEffects.objectValue();
        ENTITY_MINECART_INSIDE = SideEffects.objectValue();
        ENTITY_MINECART_RIDING = SideEffects.objectValue();
        ENTITY_MOOSHROOM_SHEAR = SideEffects.objectValue();
        ENTITY_MULE_AMBIENT = SideEffects.objectValue();
        ENTITY_MULE_CHEST = SideEffects.objectValue();
        ENTITY_MULE_DEATH = SideEffects.objectValue();
        ENTITY_MULE_HURT = SideEffects.objectValue();
        MUSIC_CREATIVE = SideEffects.objectValue();
        MUSIC_CREDITS = SideEffects.objectValue();
        MUSIC_DRAGON = SideEffects.objectValue();
        MUSIC_END = SideEffects.objectValue();
        MUSIC_GAME = SideEffects.objectValue();
        MUSIC_MENU = SideEffects.objectValue();
        MUSIC_NETHER = SideEffects.objectValue();
        BLOCK_NOTE_BASEDRUM = SideEffects.objectValue();
        BLOCK_NOTE_BASS = SideEffects.objectValue();
        BLOCK_NOTE_BELL = SideEffects.objectValue();
        BLOCK_NOTE_CHIME = SideEffects.objectValue();
        BLOCK_NOTE_FLUTE = SideEffects.objectValue();
        BLOCK_NOTE_GUITAR = SideEffects.objectValue();
        BLOCK_NOTE_HARP = SideEffects.objectValue();
        BLOCK_NOTE_HAT = SideEffects.objectValue();
        BLOCK_NOTE_PLING = SideEffects.objectValue();
        BLOCK_NOTE_SNARE = SideEffects.objectValue();
        BLOCK_NOTE_XYLOPHONE = SideEffects.objectValue();
        ENTITY_PAINTING_BREAK = SideEffects.objectValue();
        ENTITY_PAINTING_PLACE = SideEffects.objectValue();
        ENTITY_PARROT_AMBIENT = SideEffects.objectValue();
        ENTITY_PARROT_DEATH = SideEffects.objectValue();
        ENTITY_PARROT_EAT = SideEffects.objectValue();
        ENTITY_PARROT_FLY = SideEffects.objectValue();
        ENTITY_PARROT_HURT = SideEffects.objectValue();
        E_PARROT_IM_BLAZE = SideEffects.objectValue();
        E_PARROT_IM_CREEPER = SideEffects.objectValue();
        E_PARROT_IM_ELDER_GUARDIAN = SideEffects.objectValue();
        E_PARROT_IM_ENDERDRAGON = SideEffects.objectValue();
        E_PARROT_IM_ENDERMAN = SideEffects.objectValue();
        E_PARROT_IM_ENDERMITE = SideEffects.objectValue();
        E_PARROT_IM_EVOCATION_ILLAGER = SideEffects.objectValue();
        E_PARROT_IM_GHAST = SideEffects.objectValue();
        E_PARROT_IM_HUSK = SideEffects.objectValue();
        E_PARROT_IM_ILLUSION_ILLAGER = SideEffects.objectValue();
        E_PARROT_IM_MAGMACUBE = SideEffects.objectValue();
        E_PARROT_IM_POLAR_BEAR = SideEffects.objectValue();
        E_PARROT_IM_SHULKER = SideEffects.objectValue();
        E_PARROT_IM_SILVERFISH = SideEffects.objectValue();
        E_PARROT_IM_SKELETON = SideEffects.objectValue();
        E_PARROT_IM_SLIME = SideEffects.objectValue();
        E_PARROT_IM_SPIDER = SideEffects.objectValue();
        E_PARROT_IM_STRAY = SideEffects.objectValue();
        E_PARROT_IM_VEX = SideEffects.objectValue();
        E_PARROT_IM_VINDICATION_ILLAGER = SideEffects.objectValue();
        E_PARROT_IM_WITCH = SideEffects.objectValue();
        E_PARROT_IM_WITHER = SideEffects.objectValue();
        E_PARROT_IM_WITHER_SKELETON = SideEffects.objectValue();
        E_PARROT_IM_WOLF = SideEffects.objectValue();
        E_PARROT_IM_ZOMBIE = SideEffects.objectValue();
        E_PARROT_IM_ZOMBIE_PIGMAN = SideEffects.objectValue();
        E_PARROT_IM_ZOMBIE_VILLAGER = SideEffects.objectValue();
        ENTITY_PARROT_STEP = SideEffects.objectValue();
        ENTITY_PIG_AMBIENT = SideEffects.objectValue();
        ENTITY_PIG_DEATH = SideEffects.objectValue();
        ENTITY_PIG_HURT = SideEffects.objectValue();
        ENTITY_PIG_SADDLE = SideEffects.objectValue();
        ENTITY_PIG_STEP = SideEffects.objectValue();
        BLOCK_PISTON_CONTRACT = SideEffects.objectValue();
        BLOCK_PISTON_EXTEND = SideEffects.objectValue();
        ENTITY_PLAYER_ATTACK_CRIT = SideEffects.objectValue();
        ENTITY_PLAYER_ATTACK_KNOCKBACK = SideEffects.objectValue();
        ENTITY_PLAYER_ATTACK_NODAMAGE = SideEffects.objectValue();
        ENTITY_PLAYER_ATTACK_STRONG = SideEffects.objectValue();
        ENTITY_PLAYER_ATTACK_SWEEP = SideEffects.objectValue();
        ENTITY_PLAYER_ATTACK_WEAK = SideEffects.objectValue();
        ENTITY_PLAYER_BIG_FALL = SideEffects.objectValue();
        ENTITY_PLAYER_BREATH = SideEffects.objectValue();
        ENTITY_PLAYER_BURP = SideEffects.objectValue();
        ENTITY_PLAYER_DEATH = SideEffects.objectValue();
        ENTITY_PLAYER_HURT = SideEffects.objectValue();
        ENTITY_PLAYER_HURT_DROWN = SideEffects.objectValue();
        ENTITY_PLAYER_HURT_ON_FIRE = SideEffects.objectValue();
        ENTITY_PLAYER_LEVELUP = SideEffects.objectValue();
        ENTITY_PLAYER_SMALL_FALL = SideEffects.objectValue();
        ENTITY_PLAYER_SPLASH = SideEffects.objectValue();
        ENTITY_PLAYER_SWIM = SideEffects.objectValue();
        ENTITY_POLAR_BEAR_AMBIENT = SideEffects.objectValue();
        ENTITY_POLAR_BEAR_BABY_AMBIENT = SideEffects.objectValue();
        ENTITY_POLAR_BEAR_DEATH = SideEffects.objectValue();
        ENTITY_POLAR_BEAR_HURT = SideEffects.objectValue();
        ENTITY_POLAR_BEAR_STEP = SideEffects.objectValue();
        ENTITY_POLAR_BEAR_WARNING = SideEffects.objectValue();
        BLOCK_PORTAL_AMBIENT = SideEffects.objectValue();
        BLOCK_PORTAL_TRAVEL = SideEffects.objectValue();
        BLOCK_PORTAL_TRIGGER = SideEffects.objectValue();
        ENTITY_RABBIT_AMBIENT = SideEffects.objectValue();
        ENTITY_RABBIT_ATTACK = SideEffects.objectValue();
        ENTITY_RABBIT_DEATH = SideEffects.objectValue();
        ENTITY_RABBIT_HURT = SideEffects.objectValue();
        ENTITY_RABBIT_JUMP = SideEffects.objectValue();
        RECORD_11 = SideEffects.objectValue();
        RECORD_13 = SideEffects.objectValue();
        RECORD_BLOCKS = SideEffects.objectValue();
        RECORD_CAT = SideEffects.objectValue();
        RECORD_CHIRP = SideEffects.objectValue();
        RECORD_FAR = SideEffects.objectValue();
        RECORD_MALL = SideEffects.objectValue();
        RECORD_MELLOHI = SideEffects.objectValue();
        RECORD_STAL = SideEffects.objectValue();
        RECORD_STRAD = SideEffects.objectValue();
        RECORD_WAIT = SideEffects.objectValue();
        RECORD_WARD = SideEffects.objectValue();
        BLOCK_REDSTONE_TORCH_BURNOUT = SideEffects.objectValue();
        BLOCK_SAND_BREAK = SideEffects.objectValue();
        BLOCK_SAND_FALL = SideEffects.objectValue();
        BLOCK_SAND_HIT = SideEffects.objectValue();
        BLOCK_SAND_PLACE = SideEffects.objectValue();
        BLOCK_SAND_STEP = SideEffects.objectValue();
        ENTITY_SHEEP_AMBIENT = SideEffects.objectValue();
        ENTITY_SHEEP_DEATH = SideEffects.objectValue();
        ENTITY_SHEEP_HURT = SideEffects.objectValue();
        ENTITY_SHEEP_SHEAR = SideEffects.objectValue();
        ENTITY_SHEEP_STEP = SideEffects.objectValue();
        ITEM_SHIELD_BLOCK = SideEffects.objectValue();
        ITEM_SHIELD_BREAK = SideEffects.objectValue();
        ITEM_SHOVEL_FLATTEN = SideEffects.objectValue();
        ENTITY_SHULKER_AMBIENT = SideEffects.objectValue();
        BLOCK_SHULKER_BOX_CLOSE = SideEffects.objectValue();
        BLOCK_SHULKER_BOX_OPEN = SideEffects.objectValue();
        ENTITY_SHULKER_BULLET_HIT = SideEffects.objectValue();
        ENTITY_SHULKER_BULLET_HURT = SideEffects.objectValue();
        ENTITY_SHULKER_CLOSE = SideEffects.objectValue();
        ENTITY_SHULKER_DEATH = SideEffects.objectValue();
        ENTITY_SHULKER_HURT = SideEffects.objectValue();
        ENTITY_SHULKER_HURT_CLOSED = SideEffects.objectValue();
        ENTITY_SHULKER_OPEN = SideEffects.objectValue();
        ENTITY_SHULKER_SHOOT = SideEffects.objectValue();
        ENTITY_SHULKER_TELEPORT = SideEffects.objectValue();
        ENTITY_SILVERFISH_AMBIENT = SideEffects.objectValue();
        ENTITY_SILVERFISH_DEATH = SideEffects.objectValue();
        ENTITY_SILVERFISH_HURT = SideEffects.objectValue();
        ENTITY_SILVERFISH_STEP = SideEffects.objectValue();
        ENTITY_SKELETON_AMBIENT = SideEffects.objectValue();
        ENTITY_SKELETON_DEATH = SideEffects.objectValue();
        ENTITY_SKELETON_HORSE_AMBIENT = SideEffects.objectValue();
        ENTITY_SKELETON_HORSE_DEATH = SideEffects.objectValue();
        ENTITY_SKELETON_HORSE_HURT = SideEffects.objectValue();
        ENTITY_SKELETON_HURT = SideEffects.objectValue();
        ENTITY_SKELETON_SHOOT = SideEffects.objectValue();
        ENTITY_SKELETON_STEP = SideEffects.objectValue();
        ENTITY_SLIME_ATTACK = SideEffects.objectValue();
        BLOCK_SLIME_BREAK = SideEffects.objectValue();
        ENTITY_SLIME_DEATH = SideEffects.objectValue();
        BLOCK_SLIME_FALL = SideEffects.objectValue();
        BLOCK_SLIME_HIT = SideEffects.objectValue();
        ENTITY_SLIME_HURT = SideEffects.objectValue();
        ENTITY_SLIME_JUMP = SideEffects.objectValue();
        BLOCK_SLIME_PLACE = SideEffects.objectValue();
        ENTITY_SLIME_SQUISH = SideEffects.objectValue();
        BLOCK_SLIME_STEP = SideEffects.objectValue();
        ENTITY_SMALL_MAGMACUBE_DEATH = SideEffects.objectValue();
        ENTITY_SMALL_MAGMACUBE_HURT = SideEffects.objectValue();
        ENTITY_SMALL_MAGMACUBE_SQUISH = SideEffects.objectValue();
        ENTITY_SMALL_SLIME_DEATH = SideEffects.objectValue();
        ENTITY_SMALL_SLIME_HURT = SideEffects.objectValue();
        ENTITY_SMALL_SLIME_JUMP = SideEffects.objectValue();
        ENTITY_SMALL_SLIME_SQUISH = SideEffects.objectValue();
        ENTITY_SNOWBALL_THROW = SideEffects.objectValue();
        ENTITY_SNOWMAN_AMBIENT = SideEffects.objectValue();
        ENTITY_SNOWMAN_DEATH = SideEffects.objectValue();
        ENTITY_SNOWMAN_HURT = SideEffects.objectValue();
        ENTITY_SNOWMAN_SHOOT = SideEffects.objectValue();
        BLOCK_SNOW_BREAK = SideEffects.objectValue();
        BLOCK_SNOW_FALL = SideEffects.objectValue();
        BLOCK_SNOW_HIT = SideEffects.objectValue();
        BLOCK_SNOW_PLACE = SideEffects.objectValue();
        BLOCK_SNOW_STEP = SideEffects.objectValue();
        ENTITY_SPIDER_AMBIENT = SideEffects.objectValue();
        ENTITY_SPIDER_DEATH = SideEffects.objectValue();
        ENTITY_SPIDER_HURT = SideEffects.objectValue();
        ENTITY_SPIDER_STEP = SideEffects.objectValue();
        ENTITY_SPLASH_POTION_BREAK = SideEffects.objectValue();
        ENTITY_SPLASH_POTION_THROW = SideEffects.objectValue();
        ENTITY_SQUID_AMBIENT = SideEffects.objectValue();
        ENTITY_SQUID_DEATH = SideEffects.objectValue();
        ENTITY_SQUID_HURT = SideEffects.objectValue();
        BLOCK_STONE_BREAK = SideEffects.objectValue();
        BLOCK_STONE_BUTTON_CLICK_OFF = SideEffects.objectValue();
        BLOCK_STONE_BUTTON_CLICK_ON = SideEffects.objectValue();
        BLOCK_STONE_FALL = SideEffects.objectValue();
        BLOCK_STONE_HIT = SideEffects.objectValue();
        BLOCK_STONE_PLACE = SideEffects.objectValue();
        BLOCK_STONE_PRESSPLATE_CLICK_OFF = SideEffects.objectValue();
        BLOCK_STONE_PRESSPLATE_CLICK_ON = SideEffects.objectValue();
        BLOCK_STONE_STEP = SideEffects.objectValue();
        ENTITY_STRAY_AMBIENT = SideEffects.objectValue();
        ENTITY_STRAY_DEATH = SideEffects.objectValue();
        ENTITY_STRAY_HURT = SideEffects.objectValue();
        ENTITY_STRAY_STEP = SideEffects.objectValue();
        ENCHANT_THORNS_HIT = SideEffects.objectValue();
        ENTITY_TNT_PRIMED = SideEffects.objectValue();
        ITEM_TOTEM_USE = SideEffects.objectValue();
        BLOCK_TRIPWIRE_ATTACH = SideEffects.objectValue();
        BLOCK_TRIPWIRE_CLICK_OFF = SideEffects.objectValue();
        BLOCK_TRIPWIRE_CLICK_ON = SideEffects.objectValue();
        BLOCK_TRIPWIRE_DETACH = SideEffects.objectValue();
        UI_BUTTON_CLICK = SideEffects.objectValue();
        UI_TOAST_IN = SideEffects.objectValue();
        UI_TOAST_OUT = SideEffects.objectValue();
        UI_TOAST_CHALLENGE_COMPLETE = SideEffects.objectValue();
        ENTITY_VEX_AMBIENT = SideEffects.objectValue();
        ENTITY_VEX_CHARGE = SideEffects.objectValue();
        ENTITY_VEX_DEATH = SideEffects.objectValue();
        ENTITY_VEX_HURT = SideEffects.objectValue();
        ENTITY_VILLAGER_AMBIENT = SideEffects.objectValue();
        ENTITY_VILLAGER_DEATH = SideEffects.objectValue();
        ENTITY_VILLAGER_HURT = SideEffects.objectValue();
        ENTITY_VILLAGER_NO = SideEffects.objectValue();
        ENTITY_VILLAGER_TRADING = SideEffects.objectValue();
        ENTITY_VILLAGER_YES = SideEffects.objectValue();
        VINDICATION_ILLAGER_AMBIENT = SideEffects.objectValue();
        VINDICATION_ILLAGER_DEATH = SideEffects.objectValue();
        ENTITY_VINDICATION_ILLAGER_HURT = SideEffects.objectValue();
        BLOCK_WATERLILY_PLACE = SideEffects.objectValue();
        BLOCK_WATER_AMBIENT = SideEffects.objectValue();
        WEATHER_RAIN = SideEffects.objectValue();
        WEATHER_RAIN_ABOVE = SideEffects.objectValue();
        ENTITY_WITCH_AMBIENT = SideEffects.objectValue();
        ENTITY_WITCH_DEATH = SideEffects.objectValue();
        ENTITY_WITCH_DRINK = SideEffects.objectValue();
        ENTITY_WITCH_HURT = SideEffects.objectValue();
        ENTITY_WITCH_THROW = SideEffects.objectValue();
        ENTITY_WITHER_AMBIENT = SideEffects.objectValue();
        ENTITY_WITHER_BREAK_BLOCK = SideEffects.objectValue();
        ENTITY_WITHER_DEATH = SideEffects.objectValue();
        ENTITY_WITHER_HURT = SideEffects.objectValue();
        ENTITY_WITHER_SHOOT = SideEffects.objectValue();
        ENTITY_WITHER_SKELETON_AMBIENT = SideEffects.objectValue();
        ENTITY_WITHER_SKELETON_DEATH = SideEffects.objectValue();
        ENTITY_WITHER_SKELETON_HURT = SideEffects.objectValue();
        ENTITY_WITHER_SKELETON_STEP = SideEffects.objectValue();
        ENTITY_WITHER_SPAWN = SideEffects.objectValue();
        ENTITY_WOLF_AMBIENT = SideEffects.objectValue();
        ENTITY_WOLF_DEATH = SideEffects.objectValue();
        ENTITY_WOLF_GROWL = SideEffects.objectValue();
        ENTITY_WOLF_HOWL = SideEffects.objectValue();
        ENTITY_WOLF_HURT = SideEffects.objectValue();
        ENTITY_WOLF_PANT = SideEffects.objectValue();
        ENTITY_WOLF_SHAKE = SideEffects.objectValue();
        ENTITY_WOLF_STEP = SideEffects.objectValue();
        ENTITY_WOLF_WHINE = SideEffects.objectValue();
        BLOCK_WOODEN_DOOR_CLOSE = SideEffects.objectValue();
        BLOCK_WOODEN_DOOR_OPEN = SideEffects.objectValue();
        BLOCK_WOODEN_TRAPDOOR_CLOSE = SideEffects.objectValue();
        BLOCK_WOODEN_TRAPDOOR_OPEN = SideEffects.objectValue();
        BLOCK_WOOD_BREAK = SideEffects.objectValue();
        BLOCK_WOOD_BUTTON_CLICK_OFF = SideEffects.objectValue();
        BLOCK_WOOD_BUTTON_CLICK_ON = SideEffects.objectValue();
        BLOCK_WOOD_FALL = SideEffects.objectValue();
        BLOCK_WOOD_HIT = SideEffects.objectValue();
        BLOCK_WOOD_PLACE = SideEffects.objectValue();
        BLOCK_WOOD_PRESSPLATE_CLICK_OFF = SideEffects.objectValue();
        BLOCK_WOOD_PRESSPLATE_CLICK_ON = SideEffects.objectValue();
        BLOCK_WOOD_STEP = SideEffects.objectValue();
        ENTITY_ZOMBIE_AMBIENT = SideEffects.objectValue();
        ENTITY_ZOMBIE_ATTACK_DOOR_WOOD = SideEffects.objectValue();
        ENTITY_ZOMBIE_ATTACK_IRON_DOOR = SideEffects.objectValue();
        ENTITY_ZOMBIE_BREAK_DOOR_WOOD = SideEffects.objectValue();
        ENTITY_ZOMBIE_DEATH = SideEffects.objectValue();
        ENTITY_ZOMBIE_HORSE_AMBIENT = SideEffects.objectValue();
        ENTITY_ZOMBIE_HORSE_DEATH = SideEffects.objectValue();
        ENTITY_ZOMBIE_HORSE_HURT = SideEffects.objectValue();
        ENTITY_ZOMBIE_HURT = SideEffects.objectValue();
        ENTITY_ZOMBIE_INFECT = SideEffects.objectValue();
        ENTITY_ZOMBIE_PIG_AMBIENT = SideEffects.objectValue();
        ENTITY_ZOMBIE_PIG_ANGRY = SideEffects.objectValue();
        ENTITY_ZOMBIE_PIG_DEATH = SideEffects.objectValue();
        ENTITY_ZOMBIE_PIG_HURT = SideEffects.objectValue();
        ENTITY_ZOMBIE_STEP = SideEffects.objectValue();
        ENTITY_ZOMBIE_VILLAGER_AMBIENT = SideEffects.objectValue();
        ENTITY_ZOMBIE_VILLAGER_CONVERTED = SideEffects.objectValue();
        ENTITY_ZOMBIE_VILLAGER_CURE = SideEffects.objectValue();
        ENTITY_ZOMBIE_VILLAGER_DEATH = SideEffects.objectValue();
        ENTITY_ZOMBIE_VILLAGER_HURT = SideEffects.objectValue();
        ENTITY_ZOMBIE_VILLAGER_STEP = SideEffects.objectValue();
    }
}
