package dev.xdark.clientapi.entity;

import dev.xdark.clientapi.*;
import dev.xdark.clientapi.nbt.*;
import dev.xdark.clientapi.world.*;

@SidedApi(Side.SERVER)
public interface EntityProvider
{
    public static final int ITEM = 1;
    public static final int XP_ORB = 2;
    public static final int AREA_EFFECT_CLOUD = 3;
    public static final int ELDER_GUARDIAN = 4;
    public static final int WITHER_SKELETON = 5;
    public static final int STRAY = 6;
    public static final int EGG = 7;
    public static final int LEASH_KNOT = 8;
    public static final int PAINTING = 9;
    public static final int ARROW = 10;
    public static final int SNOWBALL = 11;
    public static final int FIREBALL = 12;
    public static final int SMALL_FIREBALL = 13;
    public static final int ENDER_PEARL = 14;
    public static final int EYE_OF_ENDER = 15;
    public static final int POTION = 16;
    public static final int XP_BOTTLE = 17;
    public static final int ITEM_FRAME = 18;
    public static final int WITHER_SKULL = 19;
    public static final int TNT = 20;
    public static final int FALLING_BLOCK = 21;
    public static final int FIREWORKS_ROCKET = 22;
    public static final int HUSK = 23;
    public static final int SPECTRAL_ARROW = 24;
    public static final int SHULKER_BULLET = 25;
    public static final int DRAGON_FIREBALL = 26;
    public static final int ZOMBIE_VILLAGER = 27;
    public static final int SKELETON_HORSE = 28;
    public static final int ZOMBIE_HORSE = 29;
    public static final int ARMOR_STAND = 30;
    public static final int DONKEY = 31;
    public static final int MULE = 32;
    public static final int EVOCATION_FANGS = 33;
    public static final int EVOCATION_ILLAGER = 34;
    public static final int VEX = 35;
    public static final int VINDICATION_ILLAGER = 36;
    public static final int ILLUSION_ILLAGER = 37;
    public static final int COMMANDBLOCK_MINECART = 40;
    public static final int BOAT = 41;
    public static final int MINECART = 42;
    public static final int CHEST_MINECART = 43;
    public static final int FURNACE_MINECART = 44;
    public static final int TNT_MINECART = 45;
    public static final int HOPPER_MINECART = 46;
    public static final int SPAWNER_MINECART = 47;
    public static final int CREEPER = 50;
    public static final int SKELETON = 51;
    public static final int SPIDER = 52;
    public static final int GIANT = 53;
    public static final int ZOMBIE = 54;
    public static final int SLIME = 55;
    public static final int GHAST = 56;
    public static final int ZOMBIE_PIGMAN = 57;
    public static final int ENDERMAN = 58;
    public static final int CAVE_SPIDER = 59;
    public static final int SILVERFISH = 60;
    public static final int BLAZE = 61;
    public static final int MAGMA_CUBE = 62;
    public static final int ENDER_DRAGON = 63;
    public static final int WITHER = 64;
    public static final int BAT = 65;
    public static final int WITCH = 66;
    public static final int ENDERMITE = 67;
    public static final int GUARDIAN = 68;
    public static final int SHULKER = 69;
    public static final int PIG = 90;
    public static final int SHEEP = 91;
    public static final int COW = 92;
    public static final int CHICKEN = 93;
    public static final int SQUID = 94;
    public static final int WOLF = 95;
    public static final int MOOSHROOM = 96;
    public static final int SNOWMAN = 97;
    public static final int OCELOT = 98;
    public static final int VILLAGER_GOLEM = 99;
    public static final int HORSE = 100;
    public static final int RABBIT = 101;
    public static final int POLAR_BEAR = 102;
    public static final int LLAMA = 103;
    public static final int LLAMA_SPIT = 104;
    public static final int PARROT = 105;
    public static final int VILLAGER = 120;
    public static final int ENDER_CRYSTAL = 200;
    public static final int PLAYER = 1000;
    public static final int LIGHTNING_BOLT = 1001;
    
    Entity newEntity(final NBTTagCompound info, final World world);
    
    Entity newEntity(final int id, final World world);
}
